In [1]:
import os
import firebase_admin
from firebase_admin import credentials, firestore
import vertexai
from vertexai.language_models import TextEmbeddingModel
from google.cloud import storage
import json
import time
from dotenv import load_dotenv

In [2]:
# uploading the environment variables and get the API key
load_dotenv()
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")

# Asegurar que Vertex AI use las credenciales correctas
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

BUCKET_NAME = 'embeddings_bucket_backup'
storage_client = storage.Client()
bucket = storage_client.bucket(BUCKET_NAME)

In [ ]:
# Inicialización
cred = credentials.Certificate('../../../bubbo-dfba0-47e395cdcdc7.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

PROJECT_ID = "bubbo-dfba0"
REGION = "us-central1"
MODEL_ID = "text-multilingual-embedding-002"
vertexai.init(project=PROJECT_ID, location=REGION)
model = TextEmbeddingModel.from_pretrained(MODEL_ID)

In [ ]:
#### Esta celda ELIMIMNA TODOS LOS JSON de un bucket OJO!!!
'''
from google.cloud import storage

# Inicializa el cliente
client = storage.Client()

# Nombre del bucket y prefijo de la carpeta
bucket_name = 'embeddings_new_bucket'
prefix = 'embeddings/movies_and_series/'

# Accede al bucket
bucket = client.bucket(bucket_name)

# Lista los blobs con ese prefijo
blobs = client.list_blobs(bucket_name, prefix=prefix)

# Borra solo los archivos JSON, sin eliminar carpetas
for blob in blobs:
    if blob.name.endswith('.json'):
        print(f'Eliminando: {blob.name}')
        blob.delete()

print("Archivos JSON eliminados.")
'''

Eliminando: embeddings/movies_and_series/100001460.json
Eliminando: embeddings/movies_and_series/100003875.json
Eliminando: embeddings/movies_and_series/1000046231.json
Eliminando: embeddings/movies_and_series/100005364.json
Eliminando: embeddings/movies_and_series/1000058493.json
Eliminando: embeddings/movies_and_series/100006911.json
Eliminando: embeddings/movies_and_series/100007149.json
Eliminando: embeddings/movies_and_series/100008988.json
Eliminando: embeddings/movies_and_series/100009282.json
Eliminando: embeddings/movies_and_series/100009943.json
Eliminando: embeddings/movies_and_series/100011416.json
Eliminando: embeddings/movies_and_series/100012037.json
Eliminando: embeddings/movies_and_series/100015183.json
Eliminando: embeddings/movies_and_series/100015678.json
Eliminando: embeddings/movies_and_series/100015690.json
Eliminando: embeddings/movies_and_series/100015706.json
Eliminando: embeddings/movies_and_series/100016921.json
Eliminando: embeddings/movies_and_series/100019146.json
Eliminando: embeddings/movies_and_series/100021461.json
Eliminando: embeddings/movies_and_series/100026193.json
Eliminando: embeddings/movies_and_series/100026414.json
Eliminando: embeddings/movies_and_series/100028342.json
Eliminando: embeddings/movies_and_series/10006.json
Eliminando: embeddings/movies_and_series/1004770000.json
Eliminando: embeddings/movies_and_series/100544.json
Eliminando: embeddings/movies_and_series/1007591.json
Eliminando: embeddings/movies_and_series/10135.json
Eliminando: embeddings/movies_and_series/1016213.json
Eliminando: embeddings/movies_and_series/1020581.json
Eliminando: embeddings/movies_and_series/1021332.json
Eliminando: embeddings/movies_and_series/1028493.json
Eliminando: embeddings/movies_and_series/104092.json
Eliminando: embeddings/movies_and_series/104624.json
Eliminando: embeddings/movies_and_series/1046917.json
Eliminando: embeddings/movies_and_series/10482.json
Eliminando: embeddings/movies_and_series/10487.json
Eliminando: embeddings/movies_and_series/1051486.json
Eliminando: embeddings/movies_and_series/1052158.json
Eliminando: embeddings/movies_and_series/10623.json
Eliminando: embeddings/movies_and_series/106319400408.json
Eliminando: embeddings/movies_and_series/106430.json
Eliminando: embeddings/movies_and_series/10648.json
Eliminando: embeddings/movies_and_series/10651.json
Eliminando: embeddings/movies_and_series/1071976.json
Eliminando: embeddings/movies_and_series/107270000.json
Eliminando: embeddings/movies_and_series/1073732.json
Eliminando: embeddings/movies_and_series/1083532.json
Eliminando: embeddings/movies_and_series/108789.json
Eliminando: embeddings/movies_and_series/1095814.json
Eliminando: embeddings/movies_and_series/10975.json
Eliminando: embeddings/movies_and_series/1100094.json
Eliminando: embeddings/movies_and_series/11053.json
Eliminando: embeddings/movies_and_series/1106498.json
Eliminando: embeddings/movies_and_series/1112505.json
Eliminando: embeddings/movies_and_series/111747.json
Eliminando: embeddings/movies_and_series/112051.json
Eliminando: embeddings/movies_and_series/112134.json
Eliminando: embeddings/movies_and_series/112929.json
Eliminando: embeddings/movies_and_series/1140680.json
Eliminando: embeddings/movies_and_series/1140692.json
Eliminando: embeddings/movies_and_series/114370.json
Eliminando: embeddings/movies_and_series/114620.json
Eliminando: embeddings/movies_and_series/1146434.json
Eliminando: embeddings/movies_and_series/1149779.json
Eliminando: embeddings/movies_and_series/1151694.json
Eliminando: embeddings/movies_and_series/11614570000.json
Eliminando: embeddings/movies_and_series/1162941.json
Eliminando: embeddings/movies_and_series/1168082.json
Eliminando: embeddings/movies_and_series/11691.json
Eliminando: embeddings/movies_and_series/117097.json
Eliminando: embeddings/movies_and_series/117923.json
Eliminando: embeddings/movies_and_series/118043.json
Eliminando: embeddings/movies_and_series/118368.json
Eliminando: embeddings/movies_and_series/1186947.json
Eliminando: embeddings/movies_and_series/1194788.json
Eliminando: embeddings/movies_and_series/11968.json
Eliminando: embeddings/movies_and_series/120611.json
Eliminando: embeddings/movies_and_series/120692.json
Eliminando: embeddings/movies_and_series/120713.json
Eliminando: embeddings/movies_and_series/1215162.json
Eliminando: embeddings/movies_and_series/12204180000.json
Eliminando: embeddings/movies_and_series/122270.json
Eliminando: embeddings/movies_and_series/1232863553.json
Eliminando: embeddings/movies_and_series/1237167265.json
Eliminando: embeddings/movies_and_series/123805.json
Eliminando: embeddings/movies_and_series/124180000.json
Eliminando: embeddings/movies_and_series/124742.json
Eliminando: embeddings/movies_and_series/1247662.json
Eliminando: embeddings/movies_and_series/1247708.json
Eliminando: embeddings/movies_and_series/124830.json
Eliminando: embeddings/movies_and_series/1250857.json
Eliminando: embeddings/movies_and_series/1253906.json
Eliminando: embeddings/movies_and_series/12542.json
Eliminando: embeddings/movies_and_series/1260008895.json
Eliminando: embeddings/movies_and_series/1260016798.json
Eliminando: embeddings/movies_and_series/1260018233.json
Eliminando: embeddings/movies_and_series/1260027165.json
Eliminando: embeddings/movies_and_series/1260032460.json
Eliminando: embeddings/movies_and_series/1260050301.json
Eliminando: embeddings/movies_and_series/1260105408.json
Eliminando: embeddings/movies_and_series/1260127972.json
Eliminando: embeddings/movies_and_series/1260128588.json
Eliminando: embeddings/movies_and_series/1260132398.json
Eliminando: embeddings/movies_and_series/1264736.json
Eliminando: embeddings/movies_and_series/1264958.json
Eliminando: embeddings/movies_and_series/1265119.json
Eliminando: embeddings/movies_and_series/1265120.json
Eliminando: embeddings/movies_and_series/1265862.json
Eliminando: embeddings/movies_and_series/127681.json
Eliminando: embeddings/movies_and_series/1279350.json
Eliminando: embeddings/movies_and_series/127974.json
Eliminando: embeddings/movies_and_series/12947.json
Eliminando: embeddings/movies_and_series/129841.json
Eliminando: embeddings/movies_and_series/1304930.json
Eliminando: embeddings/movies_and_series/1305787.json
Eliminando: embeddings/movies_and_series/1306269.json
Eliminando: embeddings/movies_and_series/1308417.json
Eliminando: embeddings/movies_and_series/130923.json
Eliminando: embeddings/movies_and_series/1312641.json
Eliminando: embeddings/movies_and_series/1312643.json
Eliminando: embeddings/movies_and_series/1312647.json
Eliminando: embeddings/movies_and_series/1312655.json
Eliminando: embeddings/movies_and_series/1312657.json
Eliminando: embeddings/movies_and_series/1312659.json
Eliminando: embeddings/movies_and_series/131738.json
Eliminando: embeddings/movies_and_series/1326464.json
Eliminando: embeddings/movies_and_series/1326808.json
Eliminando: embeddings/movies_and_series/1327019.json
Eliminando: embeddings/movies_and_series/132831.json
Eliminando: embeddings/movies_and_series/13294.json
Eliminando: embeddings/movies_and_series/13334.json
Eliminando: embeddings/movies_and_series/1334575.json
Eliminando: embeddings/movies_and_series/134126.json
Eliminando: embeddings/movies_and_series/134411.json
Eliminando: embeddings/movies_and_series/134620.json
Eliminando: embeddings/movies_and_series/134904.json
Eliminando: embeddings/movies_and_series/13564150000.json
Eliminando: embeddings/movies_and_series/1357559.json
Eliminando: embeddings/movies_and_series/135889.json
Eliminando: embeddings/movies_and_series/1384438.json
Eliminando: embeddings/movies_and_series/1388522.json
Eliminando: embeddings/movies_and_series/13902800000.json
Eliminando: embeddings/movies_and_series/139688.json
Eliminando: embeddings/movies_and_series/139878148.json
Eliminando: embeddings/movies_and_series/140520.json
Eliminando: embeddings/movies_and_series/140798.json
Eliminando: embeddings/movies_and_series/1409496.json
Eliminando: embeddings/movies_and_series/1409500.json
Eliminando: embeddings/movies_and_series/1409510.json
Eliminando: embeddings/movies_and_series/1412595.json
Eliminando: embeddings/movies_and_series/14131.json
Eliminando: embeddings/movies_and_series/1414211.json
Eliminando: embeddings/movies_and_series/141526.json
Eliminando: embeddings/movies_and_series/141577930.json
Eliminando: embeddings/movies_and_series/1418373.json
Eliminando: embeddings/movies_and_series/142451.json
Eliminando: embeddings/movies_and_series/142610.json
Eliminando: embeddings/movies_and_series/14275.json
Eliminando: embeddings/movies_and_series/143413.json
Eliminando: embeddings/movies_and_series/143721.json
Eliminando: embeddings/movies_and_series/144781.json
Eliminando: embeddings/movies_and_series/144842.json
Eliminando: embeddings/movies_and_series/1452.json
Eliminando: embeddings/movies_and_series/145221.json
Eliminando: embeddings/movies_and_series/1455759.json
Eliminando: embeddings/movies_and_series/1457092.json
Eliminando: embeddings/movies_and_series/1457272.json
Eliminando: embeddings/movies_and_series/1469397.json
Eliminando: embeddings/movies_and_series/1469635.json
Eliminando: embeddings/movies_and_series/1469637.json
Eliminando: embeddings/movies_and_series/1469653.json
Eliminando: embeddings/movies_and_series/1469797.json
Eliminando: embeddings/movies_and_series/1470979.json
Eliminando: embeddings/movies_and_series/1470983.json
Eliminando: embeddings/movies_and_series/1471580.json
Eliminando: embeddings/movies_and_series/1473160000.json
Eliminando: embeddings/movies_and_series/147553832.json
Eliminando: embeddings/movies_and_series/147634.json
Eliminando: embeddings/movies_and_series/1478450.json
Eliminando: embeddings/movies_and_series/1478490.json
Eliminando: embeddings/movies_and_series/1478524.json
Eliminando: embeddings/movies_and_series/1478881.json
Eliminando: embeddings/movies_and_series/1478900.json
Eliminando: embeddings/movies_and_series/148514.json
Eliminando: embeddings/movies_and_series/148836.json
Eliminando: embeddings/movies_and_series/150009.json
Eliminando: embeddings/movies_and_series/1500675.json
Eliminando: embeddings/movies_and_series/1500677.json
Eliminando: embeddings/movies_and_series/1503650.json
Eliminando: embeddings/movies_and_series/15040.json
Eliminando: embeddings/movies_and_series/1511653.json
Eliminando: embeddings/movies_and_series/1512276.json
Eliminando: embeddings/movies_and_series/1512446.json
Eliminando: embeddings/movies_and_series/1512477.json
Eliminando: embeddings/movies_and_series/151249.json
Eliminando: embeddings/movies_and_series/1512914.json
Eliminando: embeddings/movies_and_series/1513044.json
Eliminando: embeddings/movies_and_series/1513128.json
Eliminando: embeddings/movies_and_series/1513129.json
Eliminando: embeddings/movies_and_series/1514472.json
Eliminando: embeddings/movies_and_series/1514527.json
Eliminando: embeddings/movies_and_series/1514729.json
Eliminando: embeddings/movies_and_series/1516253425.json
Eliminando: embeddings/movies_and_series/1517262.json
Eliminando: embeddings/movies_and_series/1517796.json
Eliminando: embeddings/movies_and_series/1517878.json
Eliminando: embeddings/movies_and_series/1518026.json
Eliminando: embeddings/movies_and_series/151914880.json
Eliminando: embeddings/movies_and_series/1521410.json
Eliminando: embeddings/movies_and_series/1521781.json
Eliminando: embeddings/movies_and_series/1522359.json
Eliminando: embeddings/movies_and_series/1522546.json
Eliminando: embeddings/movies_and_series/1523135.json
Eliminando: embeddings/movies_and_series/1523144.json
Eliminando: embeddings/movies_and_series/1523276.json
Eliminando: embeddings/movies_and_series/152333.json
Eliminando: embeddings/movies_and_series/1523563.json
Eliminando: embeddings/movies_and_series/1523583.json
Eliminando: embeddings/movies_and_series/152670.json
Eliminando: embeddings/movies_and_series/152885.json
Eliminando: embeddings/movies_and_series/153035.json
Eliminando: embeddings/movies_and_series/153183.json
Eliminando: embeddings/movies_and_series/153847.json
Eliminando: embeddings/movies_and_series/1541033.json
Eliminando: embeddings/movies_and_series/1541037.json
Eliminando: embeddings/movies_and_series/1541057.json
Eliminando: embeddings/movies_and_series/1541061.json
Eliminando: embeddings/movies_and_series/1541063.json
Eliminando: embeddings/movies_and_series/1541083.json
Eliminando: embeddings/movies_and_series/1541085.json
Eliminando: embeddings/movies_and_series/1541195.json
Eliminando: embeddings/movies_and_series/1541211.json
Eliminando: embeddings/movies_and_series/1541301.json
Eliminando: embeddings/movies_and_series/1541345.json
Eliminando: embeddings/movies_and_series/1541474.json
Eliminando: embeddings/movies_and_series/155024.json
Eliminando: embeddings/movies_and_series/1555404.json
Eliminando: embeddings/movies_and_series/1555419.json
Eliminando: embeddings/movies_and_series/1555491.json
Eliminando: embeddings/movies_and_series/1555593.json
Eliminando: embeddings/movies_and_series/1555704.json
Eliminando: embeddings/movies_and_series/1555716.json
Eliminando: embeddings/movies_and_series/1555740.json
Eliminando: embeddings/movies_and_series/156342623.json
Eliminando: embeddings/movies_and_series/1571311.json
Eliminando: embeddings/movies_and_series/1580646.json
Eliminando: embeddings/movies_and_series/15829770000.json
Eliminando: embeddings/movies_and_series/1591463.json
Eliminando: embeddings/movies_and_series/16062.json
Eliminando: embeddings/movies_and_series/160625.json
Eliminando: embeddings/movies_and_series/16168000000.json
Eliminando: embeddings/movies_and_series/162050.json
Eliminando: embeddings/movies_and_series/1626379.json
Eliminando: embeddings/movies_and_series/1626383.json
Eliminando: embeddings/movies_and_series/1626552.json
Eliminando: embeddings/movies_and_series/1626554.json
Eliminando: embeddings/movies_and_series/1628386.json
Eliminando: embeddings/movies_and_series/1628390.json
Eliminando: embeddings/movies_and_series/1628398.json
Eliminando: embeddings/movies_and_series/1628408.json
Eliminando: embeddings/movies_and_series/163133.json
Eliminando: embeddings/movies_and_series/1639767.json
Eliminando: embeddings/movies_and_series/164157.json
Eliminando: embeddings/movies_and_series/1641651.json
Eliminando: embeddings/movies_and_series/164883.json
Eliminando: embeddings/movies_and_series/1650593.json
Eliminando: embeddings/movies_and_series/1650718.json
Eliminando: embeddings/movies_and_series/1655437.json
Eliminando: embeddings/movies_and_series/1662640.json
Eliminando: embeddings/movies_and_series/166680.json
Eliminando: embeddings/movies_and_series/167562.json
Eliminando: embeddings/movies_and_series/1678311.json
Eliminando: embeddings/movies_and_series/167886.json
Eliminando: embeddings/movies_and_series/1680419.json
Eliminando: embeddings/movies_and_series/168086.json
Eliminando: embeddings/movies_and_series/168188.json
Eliminando: embeddings/movies_and_series/168321.json
Eliminando: embeddings/movies_and_series/168445.json
Eliminando: embeddings/movies_and_series/1689513.json
Eliminando: embeddings/movies_and_series/169211.json
Eliminando: embeddings/movies_and_series/1697201.json
Eliminando: embeddings/movies_and_series/169878.json
Eliminando: embeddings/movies_and_series/1700729.json
Eliminando: embeddings/movies_and_series/1700730.json
Eliminando: embeddings/movies_and_series/1701545.json
Eliminando: embeddings/movies_and_series/170220.json
Eliminando: embeddings/movies_and_series/170696.json
Eliminando: embeddings/movies_and_series/170968.json
Eliminando: embeddings/movies_and_series/1718778.json
Eliminando: embeddings/movies_and_series/1718782.json
Eliminando: embeddings/movies_and_series/1718784.json
Eliminando: embeddings/movies_and_series/1718786.json
Eliminando: embeddings/movies_and_series/172396.json
Eliminando: embeddings/movies_and_series/172639.json
Eliminando: embeddings/movies_and_series/172797.json
Eliminando: embeddings/movies_and_series/172993.json
Eliminando: embeddings/movies_and_series/173050.json
Eliminando: embeddings/movies_and_series/1732672592.json
Eliminando: embeddings/movies_and_series/174054.json
Eliminando: embeddings/movies_and_series/174065.json
Eliminando: embeddings/movies_and_series/1742922604.json
Eliminando: embeddings/movies_and_series/174645.json
Eliminando: embeddings/movies_and_series/17525230000.json
Eliminando: embeddings/movies_and_series/175447.json
Eliminando: embeddings/movies_and_series/175919.json
Eliminando: embeddings/movies_and_series/1760401.json
Eliminando: embeddings/movies_and_series/1762756.json
Eliminando: embeddings/movies_and_series/1762758.json
Eliminando: embeddings/movies_and_series/1762760.json
Eliminando: embeddings/movies_and_series/1762762.json
Eliminando: embeddings/movies_and_series/1762780.json
Eliminando: embeddings/movies_and_series/1762784.json
Eliminando: embeddings/movies_and_series/1762786.json
Eliminando: embeddings/movies_and_series/1762790.json
Eliminando: embeddings/movies_and_series/1762794.json
Eliminando: embeddings/movies_and_series/1762796.json
Eliminando: embeddings/movies_and_series/1764993.json
Eliminando: embeddings/movies_and_series/17697510000.json
Eliminando: embeddings/movies_and_series/1769859.json
Eliminando: embeddings/movies_and_series/1769905.json
Eliminando: embeddings/movies_and_series/1769907.json
Eliminando: embeddings/movies_and_series/1770000300.json
Eliminando: embeddings/movies_and_series/1770000679.json
Eliminando: embeddings/movies_and_series/1770000917.json
Eliminando: embeddings/movies_and_series/1770000950.json
Eliminando: embeddings/movies_and_series/1770001359.json
Eliminando: embeddings/movies_and_series/1770002244.json
Eliminando: embeddings/movies_and_series/17742940000.json
Eliminando: embeddings/movies_and_series/1778996.json
Eliminando: embeddings/movies_and_series/178457.json
Eliminando: embeddings/movies_and_series/178728.json
Eliminando: embeddings/movies_and_series/1791915.json
Eliminando: embeddings/movies_and_series/1793544.json
Eliminando: embeddings/movies_and_series/17938.json
Eliminando: embeddings/movies_and_series/1794044.json
Eliminando: embeddings/movies_and_series/1794972.json
Eliminando: embeddings/movies_and_series/17996260000.json
Eliminando: embeddings/movies_and_series/180419.json
Eliminando: embeddings/movies_and_series/1811759.json
Eliminando: embeddings/movies_and_series/1816670.json
Eliminando: embeddings/movies_and_series/1816676.json
Eliminando: embeddings/movies_and_series/1820790000.json
Eliminando: embeddings/movies_and_series/1830.json
Eliminando: embeddings/movies_and_series/183048.json
Eliminando: embeddings/movies_and_series/18351670000.json
Eliminando: embeddings/movies_and_series/184027.json
Eliminando: embeddings/movies_and_series/18561.json
Eliminando: embeddings/movies_and_series/1858.json
Eliminando: embeddings/movies_and_series/185844.json
Eliminando: embeddings/movies_and_series/185885.json
Eliminando: embeddings/movies_and_series/187115.json
Eliminando: embeddings/movies_and_series/18735.json
Eliminando: embeddings/movies_and_series/187537.json
Eliminando: embeddings/movies_and_series/189003.json
Eliminando: embeddings/movies_and_series/1890695.json
Eliminando: embeddings/movies_and_series/1892126.json
Eliminando: embeddings/movies_and_series/1893251.json
Eliminando: embeddings/movies_and_series/1893289.json
Eliminando: embeddings/movies_and_series/1895932.json
Eliminando: embeddings/movies_and_series/1895934.json
Eliminando: embeddings/movies_and_series/190305.json
Eliminando: embeddings/movies_and_series/1911736.json
Eliminando: embeddings/movies_and_series/191350.json
Eliminando: embeddings/movies_and_series/1920981.json
Eliminando: embeddings/movies_and_series/1921001.json
Eliminando: embeddings/movies_and_series/192199.json
Eliminando: embeddings/movies_and_series/19267.json
Eliminando: embeddings/movies_and_series/192871.json
Eliminando: embeddings/movies_and_series/193348.json

In [52]:
import vertexai
from vertexai.language_models import TextEmbeddingModel
from google.cloud import bigquery, storage
import pandas as pd
import json
import os
import time


# Configuración
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"
PROJECT = "bubbo-dfba0"
LOCATION = "europe-southwest1"
BUCKET_NAME = "embeddings_new_bucket"
GCS_PREFIX = "embeddings/movies_and_series"
BQ_QUERY = """
    SELECT tmdb_id AS ID, title, genres, synopsis 
    FROM `bubbo-dfba0.content.best_content_translated_py`
    LIMIT 250000
    OFFSET 48615
"""
EMBEDDING_MODEL = "text-multilingual-embedding-002"
BATCH_SIZE = 11  # Solo 10 registros

# Inicializar APIs
vertexai.init(project=PROJECT, location=LOCATION)
bq_client = bigquery.Client(project=PROJECT)
storage_client = storage.Client(project=PROJECT)

# Cargar el modelo de embeddings
try:
    embedding_model = TextEmbeddingModel.from_pretrained(EMBEDDING_MODEL)
    print("Modelo de embeddings cargado correctamente.")
except Exception as e:
    print(f"Error al cargar el modelo de embeddings: {e}")
    raise

def get_data_from_bigquery():
    print("Ejecutando la consulta en BigQuery...")
    job = bq_client.query(BQ_QUERY)
    iterator = job.result()
    rows = list(iterator)

    if not rows:
        print("No se encontraron resultados.")
        return [], []

    data = [{"ID": row["ID"], "title": row["title"], "genres": row["genres"], "synopsis": row["synopsis"]} for row in rows]
    df = pd.DataFrame(data)

    return df['ID'].astype(str).tolist(), df['title'].astype(str).tolist()

def create_embeddings(texts):
    embeddings = embedding_model.get_embeddings(texts)
    return [embedding.values for embedding in embeddings]

def upload_embeddings_to_gcs(ids, titles):
    for id, text in zip(ids, titles):
        gcs_path = f"{GCS_PREFIX}/{id}.json"
        blob = storage_client.bucket(BUCKET_NAME).blob(gcs_path)

        # Validar si el archivo ya existe en GCS
        if blob.exists():
            print(f"El embedding de ID {id} ya existe en GCS. Saltando...")
            continue

        # Si no existe, generar y subir
        embedding = embedding_model.get_embeddings([text])[0].values
        time.sleep(0.4)
        with open(f"/tmp/{id}.json", "w") as f:
            json.dump({"id": id, "embedding": embedding}, f)

        blob.upload_from_filename(f"/tmp/{id}.json")
        print(f"Embedding de ID {id} subido a: {gcs_path}")

# MAIN
if __name__ == "__main__":
    ids, titles = get_data_from_bigquery()
    
    if ids:
        upload_embeddings_to_gcs(ids, titles)
    else:
        print("No se encontraron IDs para procesar.")

Modelo de embeddings cargado correctamente.
Ejecutando la consulta en BigQuery...
El embedding de ID 95894 ya existe en GCS. Saltando...
El embedding de ID 116003 ya existe en GCS. Saltando...
El embedding de ID 49988 ya existe en GCS. Saltando...
El embedding de ID 95898 ya existe en GCS. Saltando...
Embedding de ID 49990 subido a: embeddings/movies_and_series/49990.json
Embedding de ID 49992 subido a: embeddings/movies_and_series/49992.json
Embedding de ID 116057 subido a: embeddings/movies_and_series/116057.json
Embedding de ID 802384 subido a: embeddings/movies_and_series/802384.json
Embedding de ID 146933 subido a: embeddings/movies_and_series/146933.json
Embedding de ID 74979 subido a: embeddings/movies_and_series/74979.json
Embedding de ID 115903 subido a: embeddings/movies_and_series/115903.json
Embedding de ID 116101 subido a: embeddings/movies_and_series/116101.json
Embedding de ID 116095 subido a: embeddings/movies_and_series/116095.json
Embedding de ID 96769 subido a: embeddings/movies_and_series/96769.json
Embedding de ID 115951 subido a: embeddings/movies_and_series/115951.json
Embedding de ID 95920 subido a: embeddings/movies_and_series/95920.json
Embedding de ID 1197804 subido a: embeddings/movies_and_series/1197804.json
Embedding de ID 95886 subido a: embeddings/movies_and_series/95886.json
Embedding de ID 95930 subido a: embeddings/movies_and_series/95930.json
Embedding de ID 96032 subido a: embeddings/movies_and_series/96032.json
Embedding de ID 116069 subido a: embeddings/movies_and_series/116069.json
Embedding de ID 95928 subido a: embeddings/movies_and_series/95928.json
Embedding de ID 116021 subido a: embeddings/movies_and_series/116021.json
Embedding de ID 96034 subido a: embeddings/movies_and_series/96034.json
Embedding de ID 96030 subido a: embeddings/movies_and_series/96030.json
Embedding de ID 115941 subido a: embeddings/movies_and_series/115941.json
Embedding de ID 139603 subido a: embeddings/movies_and_series/139603.json
Embedding de ID 116131 subido a: embeddings/movies_and_series/116131.json
Embedding de ID 116123 subido a: embeddings/movies_and_series/116123.json
Embedding de ID 136671 subido a: embeddings/movies_and_series/136671.json
Embedding de ID 95908 subido a: embeddings/movies_and_series/95908.json
Embedding de ID 116047 subido a: embeddings/movies_and_series/116047.json
Embedding de ID 115913 subido a: embeddings/movies_and_series/115913.json
Embedding de ID 116005 subido a: embeddings/movies_and_series/116005.json
Embedding de ID 139276 subido a: embeddings/movies_and_series/139276.json
Embedding de ID 122866 subido a: embeddings/movies_and_series/122866.json
Embedding de ID 862524 subido a: embeddings/movies_and_series/862524.json
Embedding de ID 5622141 subido a: embeddings/movies_and_series/5622141.json
Embedding de ID 116171 subido a: embeddings/movies_and_series/116171.json
Embedding de ID 5855777 subido a: embeddings/movies_and_series/5855777.json
Embedding de ID 115947 subido a: embeddings/movies_and_series/115947.json
Embedding de ID 95810 subido a: embeddings/movies_and_series/95810.json
Embedding de ID 3068751 subido a: embeddings/movies_and_series/3068751.json
Embedding de ID 397116 subido a: embeddings/movies_and_series/397116.json
Embedding de ID 116121 subido a: embeddings/movies_and_series/116121.json
Embedding de ID 465629 subido a: embeddings/movies_and_series/465629.json
Embedding de ID 3135670 subido a: embeddings/movies_and_series/3135670.json
Embedding de ID 115895 subido a: embeddings/movies_and_series/115895.json
Embedding de ID 5966560 subido a: embeddings/movies_and_series/5966560.json
Embedding de ID 5903633 subido a: embeddings/movies_and_series/5903633.json
Embedding de ID 96038 subido a: embeddings/movies_and_series/96038.json
Embedding de ID 95463 subido a: embeddings/movies_and_series/95463.json
Embedding de ID 144890 subido a: embeddings/movies_and_series/144890.json
Embedding de ID 270368 subido a: embeddings/movies_and_series/270368.json
Embedding de ID 95942 subido a: embeddings/movies_and_series/95942.json
Embedding de ID 95950 subido a: embeddings/movies_and_series/95950.json
Embedding de ID 115857 subido a: embeddings/movies_and_series/115857.json
Embedding de ID 116127 subido a: embeddings/movies_and_series/116127.json
Embedding de ID 116029 subido a: embeddings/movies_and_series/116029.json
Embedding de ID 48930 subido a: embeddings/movies_and_series/48930.json
Embedding de ID 95836 subido a: embeddings/movies_and_series/95836.json
Embedding de ID 95832 subido a: embeddings/movies_and_series/95832.json
Embedding de ID 95840 subido a: embeddings/movies_and_series/95840.json
Embedding de ID 115897 subido a: embeddings/movies_and_series/115897.json
Embedding de ID 115827 subido a: embeddings/movies_and_series/115827.json
Embedding de ID 95824 subido a: embeddings/movies_and_series/95824.json
Embedding de ID 95828 subido a: embeddings/movies_and_series/95828.json
Embedding de ID 115977 subido a: embeddings/movies_and_series/115977.json
Embedding de ID 49158 subido a: embeddings/movies_and_series/49158.json
Embedding de ID 286410 subido a: embeddings/movies_and_series/286410.json
Embedding de ID 49178 subido a: embeddings/movies_and_series/49178.json
Embedding de ID 115829 subido a: embeddings/movies_and_series/115829.json
Embedding de ID 116041 subido a: embeddings/movies_and_series/116041.json
Embedding de ID 146895 subido a: embeddings/movies_and_series/146895.json
Embedding de ID 115959 subido a: embeddings/movies_and_series/115959.json
Embedding de ID 1027224 subido a: embeddings/movies_and_series/1027224.json
Embedding de ID 5903635 subido a: embeddings/movies_and_series/5903635.json
Embedding de ID 115957 subido a: embeddings/movies_and_series/115957.json
Embedding de ID 115963 subido a: embeddings/movies_and_series/115963.json
Embedding de ID 115859 subido a: embeddings/movies_and_series/115859.json
Embedding de ID 116007 subido a: embeddings/movies_and_series/116007.json
Embedding de ID 115997 subido a: embeddings/movies_and_series/115997.json
Embedding de ID 424263 subido a: embeddings/movies_and_series/424263.json
Embedding de ID 1564267 subido a: embeddings/movies_and_series/1564267.json
Embedding de ID 1564260 subido a: embeddings/movies_and_series/1564260.json
Embedding de ID 1564264 subido a: embeddings/movies_and_series/1564264.json
Embedding de ID 1564271 subido a: embeddings/movies_and_series/1564271.json
Embedding de ID 142826 subido a: embeddings/movies_and_series/142826.json
Embedding de ID 132514 subido a: embeddings/movies_and_series/132514.json
Embedding de ID 122892 subido a: embeddings/movies_and_series/122892.json
Embedding de ID 327881 subido a: embeddings/movies_and_series/327881.json
Embedding de ID 81634733 subido a: embeddings/movies_and_series/81634733.json
Embedding de ID 1090097 subido a: embeddings/movies_and_series/1090097.json
Embedding de ID 498426 subido a: embeddings/movies_and_series/498426.json
Embedding de ID 81634732 subido a: embeddings/movies_and_series/81634732.json
Embedding de ID 81690338 subido a: embeddings/movies_and_series/81690338.json
Embedding de ID 619230760273 subido a: embeddings/movies_and_series/619230760273.json
Embedding de ID 598228520292 subido a: embeddings/movies_and_series/598228520292.json
Embedding de ID 601920040406 subido a: embeddings/movies_and_series/601920040406.json
Embedding de ID 391652904210 subido a: embeddings/movies_and_series/391652904210.json
Embedding de ID 81711033 subido a: embeddings/movies_and_series/81711033.json
Embedding de ID 81634734 subido a: embeddings/movies_and_series/81634734.json
Embedding de ID 81690337 subido a: embeddings/movies_and_series/81690337.json
Embedding de ID 81559495 subido a: embeddings/movies_and_series/81559495.json
Embedding de ID 81716658 subido a: embeddings/movies_and_series/81716658.json
Embedding de ID 80016431 subido a: embeddings/movies_and_series/80016431.json
Embedding de ID 81716650 subido a: embeddings/movies_and_series/81716650.json
Embedding de ID 81600623 subido a: embeddings/movies_and_series/81600623.json
Embedding de ID 81716651 subido a: embeddings/movies_and_series/81716651.json
Embedding de ID 81600631 subido a: embeddings/movies_and_series/81600631.json
Embedding de ID 81600707 subido a: embeddings/movies_and_series/81600707.json
Embedding de ID 81600635 subido a: embeddings/movies_and_series/81600635.json
Embedding de ID 81435380 subido a: embeddings/movies_and_series/81435380.json
Embedding de ID 81736848 subido a: embeddings/movies_and_series/81736848.json
Embedding de ID 81559507 subido a: embeddings/movies_and_series/81559507.json
Embedding de ID 70038943 subido a: embeddings/movies_and_series/70038943.json
Embedding de ID 81600647 subido a: embeddings/movies_and_series/81600647.json
Embedding de ID 81559512 subido a: embeddings/movies_and_series/81559512.json
Embedding de ID 81660257 subido a: embeddings/movies_and_series/81660257.json
Embedding de ID 81600704 subido a: embeddings/movies_and_series/81600704.json
Embedding de ID 344983 subido a: embeddings/movies_and_series/344983.json
Embedding de ID 109469 subido a: embeddings/movies_and_series/109469.json
Embedding de ID 13223630 subido a: embeddings/movies_and_series/13223630.json
Embedding de ID 11188125 subido a: embeddings/movies_and_series/11188125.json
Embedding de ID 11188123 subido a: embeddings/movies_and_series/11188123.json
Embedding de ID 11389966 subido a: embeddings/movies_and_series/11389966.json
Embedding de ID 11181427 subido a: embeddings/movies_and_series/11181427.json
Embedding de ID 137629 subido a: embeddings/movies_and_series/137629.json
Embedding de ID 679302 subido a: embeddings/movies_and_series/679302.json
Embedding de ID 512979 subido a: embeddings/movies_and_series/512979.json
Embedding de ID 803603 subido a: embeddings/movies_and_series/803603.json
Embedding de ID 464063 subido a: embeddings/movies_and_series/464063.json
Embedding de ID 125390 subido a: embeddings/movies_and_series/125390.json
Embedding de ID 10438103 subido a: embeddings/movies_and_series/10438103.json
Embedding de ID 11455552 subido a: embeddings/movies_and_series/11455552.json
Embedding de ID 11622554 subido a: embeddings/movies_and_series/11622554.json
Embedding de ID 5577932 subido a: embeddings/movies_and_series/5577932.json
Embedding de ID 5982236 subido a: embeddings/movies_and_series/5982236.json
Embedding de ID 246706 subido a: embeddings/movies_and_series/246706.json
Embedding de ID 13360152 subido a: embeddings/movies_and_series/13360152.json
Embedding de ID 12261844 subido a: embeddings/movies_and_series/12261844.json
Embedding de ID 13122974 subido a: embeddings/movies_and_series/13122974.json
Embedding de ID 206290 subido a: embeddings/movies_and_series/206290.json
Embedding de ID 233499 subido a: embeddings/movies_and_series/233499.json
Embedding de ID 233501 subido a: embeddings/movies_and_series/233501.json
Embedding de ID 122750 subido a: embeddings/movies_and_series/122750.json
Embedding de ID 11203090 subido a: embeddings/movies_and_series/11203090.json
Embedding de ID 5980567 subido a: embeddings/movies_and_series/5980567.json
Embedding de ID 278609 subido a: embeddings/movies_and_series/278609.json
Embedding de ID 172359 subido a: embeddings/movies_and_series/172359.json
Embedding de ID 267746 subido a: embeddings/movies_and_series/267746.json
Embedding de ID 11847511 subido a: embeddings/movies_and_series/11847511.json
Embedding de ID 1969010 subido a: embeddings/movies_and_series/1969010.json
Embedding de ID 362405 subido a: embeddings/movies_and_series/362405.json
Embedding de ID 137641 subido a: embeddings/movies_and_series/137641.json
Embedding de ID 12160194 subido a: embeddings/movies_and_series/12160194.json
Embedding de ID 1969006 subido a: embeddings/movies_and_series/1969006.json
Embedding de ID 13260002 subido a: embeddings/movies_and_series/13260002.json
Embedding de ID 305117 subido a: embeddings/movies_and_series/305117.json
Embedding de ID 63607 subido a: embeddings/movies_and_series/63607.json
Embedding de ID 80192137 subido a: embeddings/movies_and_series/80192137.json
Embedding de ID 80191555 subido a: embeddings/movies_and_series/80191555.json
Embedding de ID 60034802 subido a: embeddings/movies_and_series/60034802.json
Embedding de ID 81404183 subido a: embeddings/movies_and_series/81404183.json
Embedding de ID 81039410 subido a: embeddings/movies_and_series/81039410.json
Embedding de ID 81611248 subido a: embeddings/movies_and_series/81611248.json
Embedding de ID 81084225 subido a: embeddings/movies_and_series/81084225.json
Embedding de ID 81271525 subido a: embeddings/movies_and_series/81271525.json
Embedding de ID 80232892 subido a: embeddings/movies_and_series/80232892.json
Embedding de ID 81564866 subido a: embeddings/movies_and_series/81564866.json
Embedding de ID 81034677 subido a: embeddings/movies_and_series/81034677.json
Embedding de ID 101338 subido a: embeddings/movies_and_series/101338.json
Embedding de ID 661677 subido a: embeddings/movies_and_series/661677.json
Embedding de ID 944399 subido a: embeddings/movies_and_series/944399.json
Embedding de ID 1362480 subido a: embeddings/movies_and_series/1362480.json
Embedding de ID 1000194 subido a: embeddings/movies_and_series/1000194.json
Embedding de ID 682344 subido a: embeddings/movies_and_series/682344.json
Embedding de ID 51252 subido a: embeddings/movies_and_series/51252.json
Embedding de ID 1280465 subido a: embeddings/movies_and_series/1280465.json
Embedding de ID 81313804 subido a: embeddings/movies_and_series/81313804.json
Embedding de ID 526231 subido a: embeddings/movies_and_series/526231.json
Embedding de ID 962920 subido a: embeddings/movies_and_series/962920.json
Embedding de ID 880313 subido a: embeddings/movies_and_series/880313.json
Embedding de ID 80013561 subido a: embeddings/movies_and_series/80013561.json
Embedding de ID 81108677 subido a: embeddings/movies_and_series/81108677.json
Embedding de ID 81259570 subido a: embeddings/movies_and_series/81259570.json
Embedding de ID 81516461 subido a: embeddings/movies_and_series/81516461.json
Embedding de ID 752618 subido a: embeddings/movies_and_series/752618.json
Embedding de ID 81037873 subido a: embeddings/movies_and_series/81037873.json
Embedding de ID 81617277 subido a: embeddings/movies_and_series/81617277.json
Embedding de ID 80227556 subido a: embeddings/movies_and_series/80227556.json
Embedding de ID 81623231 subido a: embeddings/movies_and_series/81623231.json
Embedding de ID 81248392 subido a: embeddings/movies_and_series/81248392.json
Embedding de ID 70108567 subido a: embeddings/movies_and_series/70108567.json
Embedding de ID 70069048 subido a: embeddings/movies_and_series/70069048.json
Embedding de ID 81271190 subido a: embeddings/movies_and_series/81271190.json
Embedding de ID 70243022 subido a: embeddings/movies_and_series/70243022.json
Embedding de ID 81507289 subido a: embeddings/movies_and_series/81507289.json
Embedding de ID 80245357 subido a: embeddings/movies_and_series/80245357.json
Embedding de ID 80994020 subido a: embeddings/movies_and_series/80994020.json
Embedding de ID 81718293 subido a: embeddings/movies_and_series/81718293.json
Embedding de ID 81506630 subido a: embeddings/movies_and_series/81506630.json
Embedding de ID 620883 subido a: embeddings/movies_and_series/620883.json
Embedding de ID 798223 subido a: embeddings/movies_and_series/798223.json
Embedding de ID 667282 subido a: embeddings/movies_and_series/667282.json
Embedding de ID 660464 subido a: embeddings/movies_and_series/660464.json
Embedding de ID 714737 subido a: embeddings/movies_and_series/714737.json
Embedding de ID 1229537 subido a: embeddings/movies_and_series/1229537.json
Embedding de ID 1055958 subido a: embeddings/movies_and_series/1055958.json
Embedding de ID 526946 subido a: embeddings/movies_and_series/526946.json
Embedding de ID 329569 subido a: embeddings/movies_and_series/329569.json
Embedding de ID 33293 subido a: embeddings/movies_and_series/33293.json
Embedding de ID 1021835 subido a: embeddings/movies_and_series/1021835.json
Embedding de ID 381451 subido a: embeddings/movies_and_series/381451.json
Embedding de ID 16419 subido a: embeddings/movies_and_series/16419.json
Embedding de ID 17316 subido a: embeddings/movies_and_series/17316.json
Embedding de ID 16532 subido a: embeddings/movies_and_series/16532.json
Embedding de ID 874853 subido a: embeddings/movies_and_series/874853.json
Embedding de ID 17083 subido a: embeddings/movies_and_series/17083.json
Embedding de ID 17084 subido a: embeddings/movies_and_series/17084.json
Embedding de ID 1149076 subido a: embeddings/movies_and_series/1149076.json
Embedding de ID 18059 subido a: embeddings/movies_and_series/18059.json
Embedding de ID 18078 subido a: embeddings/movies_and_series/18078.json
Embedding de ID 16570 subido a: embeddings/movies_and_series/16570.json
Embedding de ID 16503 subido a: embeddings/movies_and_series/16503.json
Embedding de ID 16548 subido a: embeddings/movies_and_series/16548.json
Embedding de ID 16983 subido a: embeddings/movies_and_series/16983.json
Embedding de ID 16482 subido a: embeddings/movies_and_series/16482.json
Embedding de ID 16582 subido a: embeddings/movies_and_series/16582.json
Embedding de ID 18049 subido a: embeddings/movies_and_series/18049.json
Embedding de ID 17226 subido a: embeddings/movies_and_series/17226.json
Embedding de ID 17397 subido a: embeddings/movies_and_series/17397.json
Embedding de ID 17298 subido a: embeddings/movies_and_series/17298.json
Embedding de ID 16707 subido a: embeddings/movies_and_series/16707.json
Embedding de ID 7554 subido a: embeddings/movies_and_series/7554.json
Embedding de ID 18094 subido a: embeddings/movies_and_series/18094.json
Embedding de ID 18175 subido a: embeddings/movies_and_series/18175.json
Embedding de ID 18060 subido a: embeddings/movies_and_series/18060.json
Embedding de ID 17068 subido a: embeddings/movies_and_series/17068.json
Embedding de ID 17070 subido a: embeddings/movies_and_series/17070.json
Embedding de ID 16826 subido a: embeddings/movies_and_series/16826.json
Embedding de ID 16824 subido a: embeddings/movies_and_series/16824.json
Embedding de ID 1024300 subido a: embeddings/movies_and_series/1024300.json
Embedding de ID 17961 subido a: embeddings/movies_and_series/17961.json
Embedding de ID 17069 subido a: embeddings/movies_and_series/17069.json
Embedding de ID 16417 subido a: embeddings/movies_and_series/16417.json
Embedding de ID 17393 subido a: embeddings/movies_and_series/17393.json
Embedding de ID 17840 subido a: embeddings/movies_and_series/17840.json
Embedding de ID 26564 subido a: embeddings/movies_and_series/26564.json
Embedding de ID 16952 subido a: embeddings/movies_and_series/16952.json
Embedding de ID 505321 subido a: embeddings/movies_and_series/505321.json
Embedding de ID 18110 subido a: embeddings/movies_and_series/18110.json
Embedding de ID 17085 subido a: embeddings/movies_and_series/17085.json
Embedding de ID 16981 subido a: embeddings/movies_and_series/16981.json
Embedding de ID 349171 subido a: embeddings/movies_and_series/349171.json
Embedding de ID 870629 subido a: embeddings/movies_and_series/870629.json
Embedding de ID 17080 subido a: embeddings/movies_and_series/17080.json
Embedding de ID 18199 subido a: embeddings/movies_and_series/18199.json
Embedding de ID 16961 subido a: embeddings/movies_and_series/16961.json
Embedding de ID 16483 subido a: embeddings/movies_and_series/16483.json
Embedding de ID 16918 subido a: embeddings/movies_and_series/16918.json
Embedding de ID 810099 subido a: embeddings/movies_and_series/810099.json
Embedding de ID 16230 subido a: embeddings/movies_and_series/16230.json
Embedding de ID 16815 subido a: embeddings/movies_and_series/16815.json
Embedding de ID 16823 subido a: embeddings/movies_and_series/16823.json
Embedding de ID 17170 subido a: embeddings/movies_and_series/17170.json
Embedding de ID 18030 subido a: embeddings/movies_and_series/18030.json

KeyboardInterrupt:

In [10]:
########## VALIDADOR
from google.cloud import bigquery, storage
import os

# Config (ajustá si estás en otro archivo)
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

PROJECT = "bubbo-dfba0"
BUCKET_NAME = "embeddings_new_bucket"
GCS_PREFIX = "embeddings/movies_and_series"

# Inicializar clientes
bq_client = bigquery.Client(project=PROJECT)
storage_client = storage.Client(project=PROJECT)

# 1. Obtener todos los IDs desde BigQuery
def get_all_ids_from_bigquery():
    query = "SELECT tmdb_id AS ID FROM `bubbo-dfba0.content.best_content_translated_py`"
    query_job = bq_client.query(query)
    results = query_job.result()
    return set(str(row.ID) for row in results)

# 2. Obtener todos los archivos existentes en GCS
def get_all_ids_in_gcs():
    bucket = storage_client.bucket(BUCKET_NAME)
    blobs = bucket.list_blobs(prefix=GCS_PREFIX + "/")
    ids_in_gcs = set()

    for blob in blobs:
        filename = blob.name.split("/")[-1]
        if filename.endswith(".json"):
            id_str = filename.replace(".json", "")
            ids_in_gcs.add(id_str)

    return ids_in_gcs

# 3. Comparar y mostrar faltantes
def find_missing_embeddings():
    print("Validando archivos en GCS contra BigQuery...")

    bq_ids = get_all_ids_from_bigquery()
    gcs_ids = get_all_ids_in_gcs()

    missing_ids = sorted(bq_ids - gcs_ids)

    print(f"Total en BigQuery: {len(bq_ids)}")
    print(f"Total en GCS: {len(gcs_ids)}")
    print(f"Faltan: {len(missing_ids)} embeddings")

    if missing_ids:
        print("Algunos ejemplos:", missing_ids[:10])

    return missing_ids

# Ejecutar validador
missing_ids = find_missing_embeddings()

Validando archivos en GCS contra BigQuery...
Total en BigQuery: 444746
Total en GCS: 444747
Faltan: 0 embeddings

In [57]:
def get_all_ids_from_bigquery_ordered():
    query = "SELECT tmdb_id AS ID FROM `bubbo-dfba0.content.best_content_translated_py` ORDER BY ID"
    query_job = bq_client.query(query)
    results = query_job.result()
    return [str(row.ID) for row in results]

# Buscar posición del ID específico
def find_position_of_id(target_id="10000"):
    all_ids = get_all_ids_from_bigquery_ordered()
    if target_id in all_ids:
        position = all_ids.index(target_id)
        print(f"El ID {target_id} está en la posición {position} (índice basado en 0).")
        return position
    else:
        print(f"El ID {target_id} no se encuentra en la tabla.")
        return None

# Llamar a la función
find_position_of_id()

El ID 10000 está en la posición 2 (índice basado en 0).

2

In [19]:
# Celda para crear el endpoint que luego usaremos para leer vertex
from google.cloud import aiplatform_v1

PROJECT  = "bubbo-dfba0"
LOCATION = "europe-southwest1"  # región soportada por Matching Engine

# 1) Cliente apuntando al endpoint regional
client = aiplatform_v1.IndexEndpointServiceClient(
    client_options={
        "api_endpoint": f"{LOCATION}-aiplatform.googleapis.com"
    }
)

# 2) Parent con la región correcta
parent = f"projects/{PROJECT}/locations/{LOCATION}"

# 3) Nombre descriptivo para tu endpoint alpha
index_endpoint = aiplatform_v1.IndexEndpoint(
    display_name="alpha-recs-movies_and_tv_shows-hnsw-europe-southwest1"
)

# 4) Verificar si ya existe
existing = client.list_index_endpoints(parent=parent)
if any(ep.display_name == index_endpoint.display_name for ep in existing):
    print("Ya existe un endpoint con ese nombre. Aborta o cambia el nombre.")
else:
    # 5) Crear
    op = client.create_index_endpoint(
        parent=parent,
        index_endpoint=index_endpoint
    )
    print("Creando endpoint…")
    ep = op.result()
    print(f"Endpoint creado: {ep.name}")

Creando endpoint…
Endpoint creado: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272

In [ ]:
# para archivo all_embeddings (previo a generar el index)

import os
import json
from google.cloud import storage

# Configuraciones
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "bubbo-dfba0-47e395cdcdc7.json"
PROJECT = "bubbo-dfba0"
BUCKET_NAME = "embeddings_new_bucket"
GCS_PREFIX = "embeddings/movies_and_series"
OUTPUT_FILE = "/tmp/all_embeddings.jsonl"
GCS_OUTPUT_PATH = "embeddings/index_data/all_embeddings.jsonl"

# Inicializar cliente
storage_client = storage.Client(project=PROJECT)
bucket = storage_client.bucket(BUCKET_NAME)

# Descargar todos los JSON y convertir a JSONL
blobs = bucket.list_blobs(prefix=GCS_PREFIX)

with open(OUTPUT_FILE, "w") as jsonl_file:
    for blob in blobs:
        if blob.name.endswith(".json"):
            content = blob.download_as_text()
            data = json.loads(content)

            if "id" in data and "embedding" in data:
                jsonl_file.write(json.dumps(data) + "\n")

# Subir el archivo consolidado a GCS
output_blob = bucket.blob(GCS_OUTPUT_PATH)
output_blob.upload_from_filename(OUTPUT_FILE)
print(f"Archivo de embeddings consolidado subido a: gs://{BUCKET_NAME}/{GCS_OUTPUT_PATH}")

In [9]:

from google.cloud import storage
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"
client = storage.Client(project="bubbo-dfba0")
blob = client.bucket("embeddings_new_bucket").blob("embeddings/index_data/all_embeddings.jsonl")

count = 0
with blob.open("rt") as stream:
    for _ in stream:
        count += 1

print(f"Líneas en all_embeddings.jsonl: {count}")

Líneas en all_embeddings.jsonl: 444746

In [11]:
# Para verificar si están normalizados los embeddings o no:

from google.cloud import storage
import json
import math


# Configurar tu proyecto
BUCKET_NAME = "embeddings_new_bucket"  # Reemplazar por tu bucket real
FILE_PATH = "embeddings/index_data/all_embeddings.jsonl"  # Archivo maestro o cualquier archivo individual

# Inicializar cliente de GCS
storage_client = storage.Client()

# Descargar y leer el archivo
bucket = storage_client.bucket(BUCKET_NAME)
blob = bucket.blob(FILE_PATH)
content = blob.download_as_text()

# Parsear el archivo línea por línea (cada línea es un JSON)
lines = content.strip().split("\n")

# Tomar hasta 100 embeddings
sample_size = min(100, len(lines))
sample_lines = lines[:sample_size]

# Calcular normas
normas = []

for line in sample_lines:
    data = json.loads(line)
    embedding = data["embedding"]
    norma = math.sqrt(sum(x**2 for x in embedding))
    normas.append(norma)

# Resultados
print(f"Normas calculadas para {sample_size} embeddings:")
for i, n in enumerate(normas):
    print(f"Embedding {i+1}: Norma = {n:.4f}")

# Análisis rápido
promedio = sum(normas) / len(normas)
print(f"\nPromedio de norma: {promedio:.4f}")

if 0.95 <= promedio <= 1.05:
    print("Parece que los embeddings están normalizados.")
else:
    print("Los embeddings NO parecen estar normalizados.")

Normas calculadas para 100 embeddings:
Embedding 1: Norma = 1.0000
Embedding 2: Norma = 1.0000
Embedding 3: Norma = 1.0000
Embedding 4: Norma = 1.0000
Embedding 5: Norma = 1.0000
Embedding 6: Norma = 1.0000
Embedding 7: Norma = 1.0000
Embedding 8: Norma = 1.0000
Embedding 9: Norma = 1.0000
Embedding 10: Norma = 1.0000
Embedding 11: Norma = 1.0000
Embedding 12: Norma = 1.0000
Embedding 13: Norma = 1.0000
Embedding 14: Norma = 1.0000
Embedding 15: Norma = 1.0000
Embedding 16: Norma = 1.0000
Embedding 17: Norma = 1.0000
Embedding 18: Norma = 1.0000
Embedding 19: Norma = 1.0000
Embedding 20: Norma = 1.0000
Embedding 21: Norma = 1.0000
Embedding 22: Norma = 1.0000
Embedding 23: Norma = 1.0000
Embedding 24: Norma = 1.0000
Embedding 25: Norma = 1.0000
Embedding 26: Norma = 1.0000
Embedding 27: Norma = 1.0000
Embedding 28: Norma = 1.0000
Embedding 29: Norma = 1.0000
Embedding 30: Norma = 1.0000
Embedding 31: Norma = 1.0000
Embedding 32: Norma = 1.0000
Embedding 33: Norma = 1.0000
Embedding 34: Norma = 1.0000
Embedding 35: Norma = 1.0000
Embedding 36: Norma = 1.0000
Embedding 37: Norma = 1.0000
Embedding 38: Norma = 1.0000
Embedding 39: Norma = 1.0000
Embedding 40: Norma = 1.0000
Embedding 41: Norma = 1.0000
Embedding 42: Norma = 1.0000
Embedding 43: Norma = 1.0000
Embedding 44: Norma = 1.0000
Embedding 45: Norma = 1.0000
Embedding 46: Norma = 1.0000
Embedding 47: Norma = 1.0000
Embedding 48: Norma = 1.0000
Embedding 49: Norma = 1.0000
Embedding 50: Norma = 1.0000
Embedding 51: Norma = 1.0000
Embedding 52: Norma = 1.0000
Embedding 53: Norma = 1.0000
Embedding 54: Norma = 1.0000
Embedding 55: Norma = 1.0000
Embedding 56: Norma = 1.0000
Embedding 57: Norma = 1.0000
Embedding 58: Norma = 1.0000
Embedding 59: Norma = 1.0000
Embedding 60: Norma = 1.0000
Embedding 61: Norma = 1.0000
Embedding 62: Norma = 1.0000
Embedding 63: Norma = 1.0000
Embedding 64: Norma = 1.0000
Embedding 65: Norma = 1.0000
Embedding 66: Norma = 1.0000
Embedding 67: Norma = 1.0000
Embedding 68: Norma = 1.0000
Embedding 69: Norma = 1.0000
Embedding 70: Norma = 1.0000
Embedding 71: Norma = 1.0000
Embedding 72: Norma = 1.0000
Embedding 73: Norma = 1.0000
Embedding 74: Norma = 1.0000
Embedding 75: Norma = 1.0000
Embedding 76: Norma = 1.0000
Embedding 77: Norma = 1.0000
Embedding 78: Norma = 1.0000
Embedding 79: Norma = 1.0000
Embedding 80: Norma = 1.0000
Embedding 81: Norma = 1.0000
Embedding 82: Norma = 1.0000
Embedding 83: Norma = 1.0000
Embedding 84: Norma = 1.0000
Embedding 85: Norma = 1.0000
Embedding 86: Norma = 1.0000
Embedding 87: Norma = 1.0000
Embedding 88: Norma = 1.0000
Embedding 89: Norma = 1.0000
Embedding 90: Norma = 1.0000
Embedding 91: Norma = 1.0000
Embedding 92: Norma = 1.0000
Embedding 93: Norma = 1.0000
Embedding 94: Norma = 1.0000
Embedding 95: Norma = 1.0000
Embedding 96: Norma = 1.0000
Embedding 97: Norma = 1.0000
Embedding 98: Norma = 1.0000
Embedding 99: Norma = 1.0000
Embedding 100: Norma = 1.0000

Promedio de norma: 1.0000
Parece que los embeddings están normalizados.

In [ ]:
#creando el index

from google.cloud import aiplatform
import os


os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"


# Inicializar el cliente
aiplatform.init(
    project="bubbo-dfba0",
    location="europe-southwest1",
    staging_bucket="gs://embeddings_new_bucket"
)

# Crear el índice utilizando el algoritmo Tree-AH
index = aiplatform.MatchingEngineIndex.create_tree_ah_index(
    display_name="index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1",
    contents_delta_uri="gs://embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl",
    dimensions=768,
    approximate_neighbors_count=250,
    distance_measure_type="COSINE_DISTANCE",
    index_update_method="STREAM_UPDATE"
)

print(f"Índice creado correctamente: {index.resource_name}")

Creating MatchingEngineIndex
Create MatchingEngineIndex backing LRO: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696/operations/7376184805609701376
MatchingEngineIndex created. Resource name: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696
To use this MatchingEngineIndex in another session:
index = aiplatform.MatchingEngineIndex('projects/75629471929/locations/europe-southwest1/indexes/355467711213469696')
Índice creado correctamente: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696

In [ ]:
# consultando google cloud storage
import gcsfs

fs = gcsfs.GCSFileSystem(token="../../../bubbo-dfba0-47e395cdcdc7.json")
with fs.open('embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl') as f:
    for i in range(5):
        print(f.readline())


fs.info('embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl')

b'{"id": "100", "embedding": [-0.0009217166807502508, -0.027816399931907654, 0.042348381131887436, 0.06346812844276428, -0.030670298263430595, 0.027489224448800087, 0.0314815454185009, 0.010220708325505257, 0.023876585066318512, 0.011568091809749603, -0.015477398410439491, -0.009889459237456322, -0.022833410650491714, -0.030152367427945137, -0.020773785188794136, -0.0022359585855156183, -0.0069099594838917255, -0.06232764944434166, 0.008681670762598515, 0.056596413254737854, -0.08407587558031082, 0.039964426308870316, 0.06256385147571564, -0.04063131660223007, -0.04794082045555115, 0.03362669423222542, 0.029440846294164658, 0.0687476098537445, 0.054691143333911896, 0.08941961079835892, -0.0009745663264766335, -0.0016498188488185406, -0.0034676860086619854, 0.026875585317611694, -0.08315390348434448, 0.021503912284970284, -0.020892759785056114, -0.003366834716871381, 0.042940638959407806, 0.06786756217479706, 0.0030169568490236998, -0.10298775881528854, -0.018486252054572105, 0.044562604278326035, -0.005196806509047747, -0.05577559024095535, -0.019362399354577065, -0.04162418842315674, 0.03611278906464577, 0.03568345308303833, 0.036726582795381546, 0.08014840632677078, -0.020520318299531937, 0.0007595983915962279, 0.06492069363594055, -0.04751620814204216, -0.01529841497540474, -0.07752961665391922, -0.005159902852028608, 0.05850867182016373, 0.01156667247414589, 0.05011157691478729, 0.017201555892825127, 0.0026869773864746094, 0.012791942805051804, 0.0064340378157794476, 0.013495705090463161, -0.02993651293218136, 0.0013461426133289933, -0.016258910298347473, -0.059470467269420624, 0.030230263248085976, 0.0329284705221653, -0.04532448574900627, -0.030386846512556076, 0.058940112590789795, -0.03956226631999016, 0.04364325851202011, -0.041122764348983765, 0.027123263105750084, -0.014802413061261177, 0.06079861894249916, -0.014512622728943825, -0.013911280781030655, 0.10233696550130844, 0.0028332173824310303, -0.026674890890717506, -0.08882984519004822, 0.015233462676405907, -0.018080512061715126, 0.010874303989112377, -0.02919517084956169, -0.005165057256817818, -0.012813831679522991, -0.03137547895312309, -0.03126656264066696, 0.0336809866130352, 0.027993127703666687, -0.02338244952261448, -0.05042675510048866, 0.021559258922934532, -0.0075604566372931, -0.029185611754655838, -0.026718255132436752, 0.06175490841269493, -0.03266606107354164, 0.00013549851428251714, 0.04625151678919792, -0.024181609973311424, 0.050965603440999985, 0.01848941296339035, -0.0065552107989788055, -0.05680283531546593, 0.028222311288118362, -0.001927254954352975, 0.009210032410919666, -0.03809411823749542, 0.015946798026561737, -0.050424959510564804, -0.01533369068056345, 0.03970729932188988, 0.007282438222318888, 0.0026067099533975124, -0.010899808257818222, 0.02226468361914158, -0.04686913266777992, 0.01821923442184925, -0.04251403734087944, 0.024637481197714806, 0.0005009289598092437, 0.015452218241989613, 0.045840583741664886, 0.029497109353542328, -0.042612217366695404, -0.042879585176706314, 0.052066873759031296, 0.024753648787736893, -0.029821844771504402, -0.002698535332456231, 0.03233620896935463, -0.030500484630465508, 0.07611006498336792, 0.04427481070160866, -0.03318718820810318, -0.018006326630711555, -0.04223021864891052, -0.03480387479066849, 0.012991771101951599, 0.031224364414811134, 0.06584592163562775, -0.020902389660477638, -0.035066816955804825, -0.051799625158309937, -0.0013433978892862797, 0.023796143010258675, -0.017174959182739258, 0.018132219091057777, 0.0017778623150661588, 0.08183728903532028, -0.06674226373434067, -0.014023694209754467, -0.04052937030792236, -0.01885250024497509, 0.07497001439332962, 0.02109067142009735, -0.00688131945207715, 0.05884692817926407, 0.009445770643651485, 0.027886975556612015, -0.0508052334189415, -0.034446168690919876, 0.03466735780239105, -0.0010553045431151986, 0.017650559544563293, 0.017024265602231026, 0.0397530198097229, 0.02107134275138378, 0.03146655112504959, 0.019339151680469513, -0.049614857882261276, 0.03469376266002655, 0.022682195529341698, -0.028618114069104195, 0.06096822768449783, -0.08967741578817368, -0.003356422996148467, 0.011754038743674755, -0.0037724280264228582, 0.020850330591201782, 0.006134416908025742, -0.019993623718619347, -0.03395552933216095, 0.008478114381432533, -0.015956584364175797, -0.02770540490746498, 0.0745919719338417, 0.009194615297019482, -0.01881750114262104, -0.06566599756479263, -0.03591601550579071, -0.03827187046408653, -0.0664638951420784, 0.01352955773472786, -0.00865687895566225, -0.013701502233743668, 0.01210640650242567, 0.008359873667359352, 0.03845156356692314, 0.004356013610959053, 0.04912031814455986, 0.008728794753551483, -0.06607989221811295, -0.02665093168616295, 0.04367655888199806, -0.028053458780050278, -0.001378255314193666, 0.05190173164010048, -0.11265579611063004, -0.03252829611301422, -0.03075668029487133, -0.04016784206032753, -0.12758541107177734, -0.012522004544734955, 0.05183107778429985, -0.010352280922234058, -0.024503687396645546, -0.14181964099407196, 0.06097407266497612, -0.040963657200336456, 0.042191408574581146, 0.05985138565301895, 0.010707567445933819, -0.0538703016936779, -0.0289749875664711, -0.03046250529587269, -0.02143947221338749, 0.04782417044043541, -0.0870312973856926, 0.04627490043640137, -0.01659521460533142, -0.014466645196080208, 0.05352461710572243, 0.04014008119702339, 0.001876594964414835, -0.022489918395876884, -0.008442364633083344, 0.024627376347780228, 0.02278313599526882, 0.036717407405376434, 0.012897714041173458, 0.0016485040541738272, -0.026040423661470413, -0.024762358516454697, -0.041957419365644455, -0.049243517220020294, -0.03390040993690491, 0.020379818975925446, 0.03814476355910301, -0.04070119932293892, 0.04283924028277397, -0.01322109717875719, 0.043020449578762054, 0.0325288288295269, -0.021718762814998627, -0.00219733826816082, -0.0018562809564173222, -0.019643574953079224, -0.018180612474679947, -0.016655853018164635, 0.12390592694282532, 0.012447146698832512, 0.08859261870384216, 0.003834039904177189, -0.010705772787332535, -0.026941178366541862, 0.016808753833174706, -0.023756487295031548, 0.010189628228545189, -0.07019215822219849, 0.05037800967693329, -0.006690886337310076, -0.013998457230627537, -0.0004678698896896094, 0.04834148287773132, -0.017119184136390686, 0.020891888067126274, -0.05317467823624611, 0.021929433569312096, 0.024931270629167557, 0.028618885204195976, 0.010965608060359955, 0.008637670427560806, -0.011193189769983292, -0.002130002249032259, 0.014836996793746948, 0.06381525844335556, -0.04377171769738197, 0.009738837368786335, -0.022817222401499748, 0.016177216544747353, 0.062394190579652786, 0.0011421351227909327, -0.04605142027139664, 0.035928014665842056, 0.0010498873889446259, 0.032238781452178955, -0.006367798428982496, 0.005840805359184742, -0.0470854751765728, 0.012079047970473766, -0.01652444340288639, -0.002462429692968726, -0.005335427820682526, -0.025605520233511925, 0.016597429290413857, -0.004798599518835545, -0.017099810764193535, 0.02820957638323307, -0.014606938697397709, -0.0033952523954212666, -0.0257173590362072, 0.00299259927123785, -0.06720662117004395, 0.04293326660990715, 0.0014027045108377934, -0.005852058995515108, 0.022187432274222374, -0.00833679735660553, -0.023967646062374115, 0.05741932988166809, 0.015937361866235733, 0.009861520491540432, -0.014224857091903687, 0.007079530507326126, -0.015132513828575611, -0.012689391151070595, 0.060660477727651596, -0.018545910716056824, -0.004170672036707401, 0.08784876018762589, 0.014740211889147758, -0.008282092399895191, 0.0011443474795669317, -0.01933734118938446, 0.0037872607354074717, -0.032563310116529465, 0.05807223170995712, -0.04167341813445091, 0.05433082580566406, -0.014733350835740566, 0.007238670252263546, 0.040385983884334564, -0.008419683203101158, -0.08979463577270508, -0.0017884274711832404, 0.07238983362913132, 0.014221370220184326, 0.013908515684306622, -0.04955306276679039, 0.013516579754650593, 0.011410343460738659, -0.03534772992134094, 0.0007760213920846581, 0.00585224200040102, -0.009621932171285152, -0.003870810614898801, 0.0294390469789505, 0.00824795849621296, -0.04314916953444481, -0.04139428213238716, -0.0619315542280674, 0.05427068844437599, 0.014309081248939037, -0.027876948937773705, 0.03419267013669014, 0.026185061782598495, -0.006157968658953905, 0.004059723578393459, -0.025487765669822693, -0.0007510966970585287, 0.012131982482969761, 0.01838885433971882, 0.004199801478534937, 0.023860057815909386, -0.023773644119501114, -0.00044666099711321294, 0.04302719607949257, -0.061828579753637314, 0.014414941892027855, -0.011338042095303535, 0.035593852400779724, -0.031119629740715027, 0.008947611786425114, 0.019893789663910866, 0.0033858558163046837, 0.03883621469140053, -0.031109405681490898, -0.007827810011804104, -0.019891466945409775, 0.023330574855208397, 0.05795729160308838, -0.03222137317061424, -0.005029918160289526, -0.010957052931189537, -0.018676966428756714, 0.009247912093997002, -0.009849912486970425, 0.03652336820960045, -0.03782351687550545, -0.024964844807982445, 0.07339705526828766, -0.05546306073665619, -0.04576821252703667, -0.022262269631028175, -0.07900889217853546, -0.009290996007621288, -0.0014157341793179512, -0.005211435258388519, 0.06259189546108246, -0.03495035320520401, 0.01149998139590025, -0.04869115725159645, 0.025420021265745163, 0.02061697654426098, 0.020997297018766403, 0.01392487995326519, 0.06601167470216751, 0.011459769681096077, 0.0644971951842308, 0.05089813098311424, 0.023188509047031403, -0.00726065831258893, 0.0005174067919142544, -0.007138718850910664, 0.037492670118808746, -0.0066526769660413265, 0.009817284531891346, -0.041509900242090225, -0.04358835890889168, -0.003930828534066677, 0.007561029866337776, -0.04437461122870445, -0.0053267222829163074, -0.05802459269762039, -0.01410958357155323, -0.000517042470164597, 0.01812685839831829, 0.021740121766924858, 0.0049219075590372086, 0.05620935559272766, -0.0038143182173371315, -0.013157164677977562, 0.049148354679346085, 0.027664341032505035, 0.033590517938137054, 0.002431803848594427, -0.007216442842036486, 0.01921246200799942, 0.019745197147130966, 0.03395551070570946, 0.013996622525155544, -0.09791717678308487, 0.03244621679186821, -0.004360944498330355, 0.006118112243711948, 0.007711214944720268, 0.03310619667172432, -0.04610039293766022, -0.006557852029800415, -0.0029208713676780462, -0.020168403163552284, -0.016402577981352806, 0.020611507818102837, 0.032257139682769775, 0.021215014159679413, -0.006740160286426544, 0.01240026019513607, 0.07499559223651886, 0.026954710483551025, -0.04006706923246384, 0.004638905171304941, 0.0010122627718374133, 0.09215783327817917, 0.03234955295920372, -0.07004483044147491, -0.01034390926361084, 0.007473781704902649, -0.05814054235816002, -0.02226693369448185, 0.02521611750125885, -0.023186007514595985, 0.006680999882519245, -0.014957662671804428, -0.016951818019151688, -0.023879792541265488, -0.011090198531746864, 0.037156544625759125, 0.021576734259724617, 0.007327165454626083, -0.013056324794888496, 0.008392523974180222, -0.0313173346221447, -0.05991150438785553, 0.04444141313433647, 0.02033878304064274, -0.022826099768280983, -0.06005522236227989, -0.015444092452526093, 0.01543578039854765, -0.013917041942477226, 0.0032761823385953903, 0.0576808862388134, 0.016885260120034218, -0.03373374789953232, 0.018559593707323074, -0.01699254848062992, 0.02981572411954403, 0.008293963968753815, -0.009671326726675034, -0.008478367701172829, -0.046793725341558456, 0.10495970398187637, 0.016289589926600456, 0.02899232506752014, -0.020764393731951714, -0.022793427109718323, -0.005370027385652065, -0.05687502399086952, -0.021697593852877617, 0.010455457493662834, -0.030421309173107147, -0.029065024107694626, -0.04031390696763992, 0.030686650425195694, -0.009876763448119164, 0.06721555441617966, -0.05371361970901489, 0.048568520694971085, 0.021099867299199104, -0.03743133321404457, -0.0012799176620319486, -0.025244969874620438, -0.009059988893568516, -0.024912765249609947, 0.05236614868044853, 0.005713790189474821, -0.0061571476981043816, -0.022104425355792046, -0.04662907496094704, 0.05568473041057587, 0.01476152054965496, -0.0453607514500618, -0.023828774690628052, -0.019155994057655334, -0.02234015241265297, -0.06715407222509384, 0.0153026869520545, 0.01566164754331112, 0.038634058088064194, -0.012578827328979969, -0.04908118396997452, -0.0045433673076331615, 0.009043521247804165, -0.01420271024107933, 0.045082367956638336, -0.03142059966921806, 0.0019654836505651474, 0.02769157662987709, -0.041538842022418976, -0.004980428144335747, -0.10383102297782898, 0.004927793052047491, -0.013822969049215317, 0.020477546378970146, 0.04011811316013336, 0.016311971470713615, -0.04384680092334747, -0.01439171563833952, -0.03947516530752182, -0.014931161887943745, -0.003356784349307418, -0.05403757095336914, 0.07158895581960678, -0.0731104165315628, -0.017404986545443535, -0.038762643933296204, -0.015084169805049896, 0.025681525468826294, -0.020453117787837982, -0.05256364122033119, 0.014938692562282085, 0.015311780385673046, -0.01694396883249283, 0.05903052166104317, 0.0006505953497253358, -0.04628351703286171, 0.008903121575713158, 0.020999012514948845, 0.04112906754016876, -0.03888577222824097, 0.006931870710104704, 0.003713684156537056, 0.03922278806567192, -0.006921706255525351, 0.015252682380378246, 0.012399488128721714, 0.07252249121665955, -0.013342656195163727, -0.00174096436239779, -0.017307879403233528, -0.026519775390625, -0.00641930615529418, -0.035633642226457596, 0.0063712624832987785, 0.01633306033909321, -0.0665520653128624, -0.0008031941251829267, 0.009044324047863483, -0.02392493188381195, 0.03780888393521309, -0.038904499262571335, 0.014209412038326263, 0.04008980095386505, -0.001954104984179139, 0.04767129570245743, -0.024575814604759216, -0.036129165440797806, 0.0011571909999474883, -0.03563236445188522, -0.025437260046601295, 0.023959709331393242, 0.016507236286997795, 0.002823981223627925, -0.0706430971622467, 0.015400432050228119, 0.05975256860256195, 0.04126853868365288, 0.0272964034229517, 0.024054234847426414, 0.02307109162211418, 0.07174000144004822, 0.09567534923553467, 0.006418695207685232, 0.010161120444536209, 0.020141277462244034, 0.03624943271279335, 0.03666321560740471, 0.028910038992762566, 0.049928296357393265, -0.060796719044446945, -0.010952095501124859, 0.02233629673719406, 0.009665806777775288, -0.02752256952226162, 0.029436618089675903, 0.01548680942505598, 0.008681869134306908, -0.05344419181346893, -0.008353126235306263, 0.0020069133024662733, 0.04656665772199631, -0.038513969630002975, -0.03981463238596916, 0.03334716707468033, -0.001106441137380898, 0.0033315466716885567, 0.004331724718213081, -0.00686954939737916, -0.00884385034441948, -0.019680902361869812, -0.026334062218666077, 0.01683932915329933, -0.0070899538695812225, 0.008772997185587883, 0.0613924004137516, 0.055267658084630966, 0.01794305071234703, -0.02100851759314537, 0.08905358612537384, 0.04296343773603439, -0.028831951320171356, 0.04332193732261658, -0.0009546049986965954, -0.0032539968378841877, 0.03153934329748154, -0.029617514461278915, 0.0008956799283623695, 0.006790990009903908, -0.019577104598283768, -0.039136044681072235, -0.046653252094984055, -0.046407077461481094, 0.06149129569530487, -0.037748366594314575, 0.06492961943149567, -0.04789922758936882, 0.0153989652171731, -0.07126404345035553, 0.040268220007419586, -0.004550508689135313, -0.01878177933394909, -0.008173724636435509, -0.0561586394906044, 0.019185995683073997, 0.0005209207301959395, 0.007082770112901926, 0.007676938083022833, -0.046233586966991425, -0.005629011895507574, 0.01037396490573883, -0.02547580562531948, -0.03491021320223808, 0.009461063891649246, 0.04940834268927574, 0.0024844093713909388, 0.004990256391465664, 0.05721823498606682, -0.026086818426847458, 0.016294915229082108, 0.0413874015212059, 0.05507827177643776, 0.023656783625483513, 0.01929851435124874, 0.05706740543246269, 0.0317055881023407, 0.0423477478325367, 0.012984033674001694, -0.009340335614979267, -0.03611397743225098, 0.013398868031799793, -0.01343697588890791, -0.021457046270370483, -0.017227770760655403, 0.0013712483923882246, -0.033608391880989075, 0.04034360870718956, -0.014754705131053925, 0.009214619174599648, 0.039282169193029404, 0.015464452095329762, -0.014067542739212513, -0.006850104313343763, -0.028251511976122856, 0.042318619787693024, 0.0010159544181078672, -0.07910285890102386, -0.05739985778927803, -0.014814876019954681, -0.013562212698161602, -0.010929439216852188, -0.044873498380184174, -0.029638737440109253, 0.018473532050848007, 0.04032357782125473, -0.01731247454881668, 0.004057781305164099, -0.014460071921348572, -0.04746546223759651, -0.022014109417796135, -0.010901376605033875, -0.004708027932792902, -0.03543029725551605, 0.0077417166903615, -0.02296663261950016, 0.03288859501481056, 0.014409753493964672, -0.005033222958445549, 0.027523403987288475]}\n'

{'kind': 'storage#object',
 'id': 'embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl/1745625619779970',
 'selfLink': 'https://www.googleapis.com/storage/v1/b/embeddings_new_bucket/o/embeddings%2Findex_data%2Fall_embeddings.jsonl',
 'mediaLink': 'https://storage.googleapis.com/download/storage/v1/b/embeddings_new_bucket/o/embeddings%2Findex_data%2Fall_embeddings.jsonl?generation=1745625619779970&alt=media',
 'name': 'embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl',
 'bucket': 'embeddings_new_bucket',
 'generation': '1745625619779970',
 'metageneration': '1',
 'contentType': 'application/octet-stream',
 'storageClass': 'STANDARD',
 'size': 7565450444,
 'md5Hash': 'UDfXr+8CMIEjUj2JdahhDw==',
 'crc32c': 'G9OOIQ==',
 'etag': 'CIKj6Zey9IwDEAE=',
 'timeCreated': '2025-04-26T00:00:19.789Z',
 'updated': '2025-04-26T00:00:19.789Z',
 'timeStorageClassUpdated': '2025-04-26T00:00:19.789Z',
 'timeFinalized': '2025-04-26T00:00:19.789Z',
 'type': 'file',
 'mtime': datetime.datetime(2025, 4, 26, 0, 0, 19, 789000, tzinfo=datetime.timezone.utc),
 'ctime': datetime.datetime(2025, 4, 26, 0, 0, 19, 789000, tzinfo=datetime.timezone.utc)}

In [ ]:


import json
import gcsfs

# Inicializar GCS
fs = gcsfs.GCSFileSystem(token="../../../bubbo-dfba0-47e395cdcdc7.json")

# Ruta al archivo en GCS
file_path = 'embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl'

# Leer y validar dimensiones
with fs.open(file_path, 'r') as f:
    for i in range(5):  # Solo mostramos las primeras 5 líneas
        line = f.readline()
        data = json.loads(line)
        print(f"Línea {i + 1}: ID = {data['id']}, Dimensión = {len(data['embedding'])}")

Línea 1: ID = 100, Dimensión = 768
Línea 2: ID = 1000, Dimensión = 768
Línea 3: ID = 10000, Dimensión = 768
Línea 4: ID = 100000, Dimensión = 768
Línea 5: ID = 1000000, Dimensión = 768

In [12]:
from google.cloud import aiplatform

aiplatform.init(
    project="bubbo-dfba0",
    location="europe-southwest1",
)

# Verificar si el índice existe
index = aiplatform.MatchingEngineIndex.list()
for idx in index:
    print(idx.display_name)

index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1

In [14]:
from google.cloud import aiplatform

aiplatform.init(
    project="bubbo-dfba0",
    location="europe-southwest1",
)

# Listar los índices creados
indices = aiplatform.MatchingEngineIndex.list()
for idx in indices:
    print(f"Índice encontrado: {idx.display_name}, Resource Name: {idx.resource_name}")

Índice encontrado: index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1, Resource Name: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696

In [16]:
# Acceder al primer índice de la lista
if indices:
    index = indices[0]  # Selecciona el primer índice (ajusta según el índice que necesites)

    # Consultar los detalles completos del índice
    print(index.gca_resource)  # Esto te dará detalles completos del recurso del índice.
else:
    print("No se encontraron índices.")

name: "projects/75629471929/locations/europe-southwest1/indexes/355467711213469696"
display_name: "index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1"
metadata_schema_uri: "gs://google-cloud-aiplatform/schema/matchingengine/metadata/nearest_neighbor_search_1.0.0.yaml"
metadata {
  struct_value {
    fields {
      key: "config"
      value {
        struct_value {
          fields {
            key: "shardSize"
            value {
              string_value: "SHARD_SIZE_MEDIUM"
            }
          }
          fields {
            key: "distanceMeasureType"
            value {
              string_value: "COSINE_DISTANCE"
            }
          }
          fields {
            key: "dimensions"
            value {
              number_value: 768
            }
          }
          fields {
            key: "approximateNeighborsCount"
            value {
              number_value: 250
            }
          }
          fields {
            key: "algorithmConfig"
            value {
              struct_value {
                fields {
                  key: "treeAhConfig"
                  value {
                    struct_value {
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
etag: "AMEw9yN02HAS4wWV4wRBtaxtVilGOMBTdJNqNKIXWePoDaURKscg27MZu8MrGZxl066f"
create_time {
  seconds: 1746208657
  nanos: 703862000
}
update_time {
  seconds: 1746208700
  nanos: 706213000
}
index_stats {
  shards_count: 1
}
index_update_method: STREAM_UPDATE
encryption_spec {
}

In [17]:
index = aiplatform.MatchingEngineIndex(index_name="projects/75629471929/locations/europe-southwest1/indexes/355467711213469696")
print(index.gca_resource)

name: "projects/75629471929/locations/europe-southwest1/indexes/355467711213469696"
display_name: "index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1"
metadata_schema_uri: "gs://google-cloud-aiplatform/schema/matchingengine/metadata/nearest_neighbor_search_1.0.0.yaml"
metadata {
  struct_value {
    fields {
      key: "config"
      value {
        struct_value {
          fields {
            key: "shardSize"
            value {
              string_value: "SHARD_SIZE_MEDIUM"
            }
          }
          fields {
            key: "distanceMeasureType"
            value {
              string_value: "COSINE_DISTANCE"
            }
          }
          fields {
            key: "dimensions"
            value {
              number_value: 768
            }
          }
          fields {
            key: "approximateNeighborsCount"
            value {
              number_value: 250
            }
          }
          fields {
            key: "algorithmConfig"
            value {
              struct_value {
                fields {
                  key: "treeAhConfig"
                  value {
                    struct_value {
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
etag: "AMEw9yOaKPPnwdtAxZ4Dp4-xeQMCSOE554cvOYj227E7k1PAWD_dgPDjP99jVv8WFBFX"
create_time {
  seconds: 1746208657
  nanos: 703862000
}
update_time {
  seconds: 1746208700
  nanos: 706213000
}
index_stats {
  shards_count: 1
}
index_update_method: STREAM_UPDATE
encryption_spec {
}

In [18]:
# Ejecutando una búsqueda en el índice
search_results = index.find_neighbors(
    queries=[[0.1, 0.2, 0.3, ..., 0.768]],  # Reemplazar con un vector de consulta real
    num_neighbors=5  # Puedes ajustar este número según lo que quieras
)

print(search_results)

AttributeError: 'MatchingEngineIndex' object has no attribute 'find_neighbors'

In [ ]:
import os
import time
from google.cloud import aiplatform
from google.cloud import storage

# === CONFIGURACIÓN ===
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

PROJECT = "bubbo-dfba0"
LOCATION = "europe-southwest1"
STAGING_BUCKET = "gs://embeddings_new_bucket"
INDEX_NAME = "index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1"
INDEX_URI = "gs://embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl"
DIMENSIONS = 768
ENDPOINT_ID = "5785049643217846272"  # indexEndpoint ya existente
EXPECTED_COUNT = 440_000

# === INICIAR PLATAFORMA ===
aiplatform.init(project=PROJECT, location=LOCATION, staging_bucket=STAGING_BUCKET)

# === VALIDAR: CANTIDAD DE EMBEDDINGS EN EL ARCHIVO ===
def count_jsonl_lines(bucket_name, blob_path):
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    with blob.open("rt") as f:
        return sum(1 for _ in f)

bucket_name = "embeddings_new_bucket"
blob_path = "embeddings/index_data/all_embeddings.jsonl"
line_count = count_jsonl_lines(bucket_name, blob_path)
print(f"Embeddings detectados en JSONL: {line_count}")
if line_count < EXPECTED_COUNT:
    raise ValueError(f"❌ Archivo incompleto. Solo hay {line_count} embeddings, se esperaban al menos {EXPECTED_COUNT}.")

# === BUSCAR Y ELIMINAR ÍNDICE EXISTENTE (SI HAY UNO) ===
existing_indexes = aiplatform.MatchingEngineIndex.list(filter=f'display_name="{INDEX_NAME}"')
for existing in existing_indexes:
    print(f"Borrando índice previo: {existing.resource_name}")
    existing.delete()
    existing.wait()

# === CREAR NUEVO ÍNDICE ===
start = time.time()
index = aiplatform.MatchingEngineIndex.create_tree_ah_index(
    display_name=INDEX_NAME,
    contents_delta_uri=INDEX_URI,
    dimensions=DIMENSIONS,
    approximate_neighbors_count=250,
    distance_measure_type="COSINE_DISTANCE",
    index_update_method="STREAM_UPDATE"
)
index.wait()
elapsed = time.time() - start
print(f"✅ Índice creado en {elapsed / 60:.1f} minutos: {index.resource_name}")

Embeddings detectados en JSONL: 444746
Borrando índice previo: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696
Deleting MatchingEngineIndex : projects/75629471929/locations/europe-southwest1/indexes/355467711213469696
MatchingEngineIndex deleted. . Resource name: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696
Deleting MatchingEngineIndex resource: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696
Delete MatchingEngineIndex backing LRO: projects/75629471929/locations/europe-southwest1/indexes/355467711213469696/operations/2975605019715305472
MatchingEngineIndex resource projects/75629471929/locations/europe-southwest1/indexes/355467711213469696 deleted.
Creating MatchingEngineIndex
Create MatchingEngineIndex backing LRO: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296/operations/7099776378479837184
MatchingEngineIndex created. Resource name: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296
To use this MatchingEngineIndex in another session:
index = aiplatform.MatchingEngineIndex('projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296')
✅ Índice creado en 0.7 minutos: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296
Desplegando índice en endpoint 5785049643217846272...

TypeError: MatchingEngineIndexEndpoint.deploy_index() got an unexpected keyword argument 'traffic_split'

In [22]:
import re
# === DESPLEGAR EL ÍNDICE EN EL ENDPOINT EXISTENTE ===
endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name=ENDPOINT_ID)


deployed_index_id = re.sub(r'[^a-zA-Z0-9_]', '_', INDEX_NAME)
if not deployed_index_id[0].isalpha():
    deployed_index_id = f"a_{deployed_index_id}"
deployed_index_id = deployed_index_id[:63]

print(f"Desplegando índice en endpoint {ENDPOINT_ID}...")

endpoint.deploy_index(
    index=index,
    deployed_index_id=deployed_index_id,
    display_name="deployed-alpha-index",
    )
print(f"🚀 Índice desplegado exitosamente en endpoint: {ENDPOINT_ID}")

Desplegando índice en endpoint 5785049643217846272...
Deploying index MatchingEngineIndexEndpoint index_endpoint: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
Deploy index MatchingEngineIndexEndpoint index_endpoint backing LRO: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272/operations/1822683515108458496
MatchingEngineIndexEndpoint index_endpoint Deployed index. Resource name: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
🚀 Índice desplegado exitosamente en endpoint: 5785049643217846272

In [29]:
import json
import random
from google.cloud import storage

# === Cargar un embedding real del archivo JSONL ===
bucket_name = "embeddings_new_bucket"
blob_path = "embeddings/index_data/all_embeddings.jsonl"

client = storage.Client()
bucket = client.bucket(bucket_name)
blob = bucket.blob(blob_path)

# Leer algunas líneas y elegir una al azar
with blob.open("rt") as f:
    lines = [next(f) for _ in range(100)]  # lee 100 líneas
sample = json.loads(random.choice(lines))
query_embedding = sample["embedding"]
print(f"ID original: {sample['id']}")

ID original: 100000114

In [40]:
from google.cloud import aiplatform

aiplatform.init(project="bubbo-dfba0", location="europe-southwest1")

endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name="5785049643217846272")

response = endpoint.find_neighbors(
    deployed_index_id="index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe",
    queries=[query_embedding],
    num_neighbors=5,
)

# Verifica que la respuesta tenga datos antes de intentar iterar
if response and len(response[0]) > 0:
    for idx, neighbor in enumerate(response[0]):
        print(f"ID: {neighbor.distance:2.f}, {product_names[neighbor.id]}")
else:
    print("No se encontraron vecinos para la consulta.")

No se encontraron vecinos para la consulta.

In [43]:
endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name="5785049643217846272")

for deployed_index in endpoint.deployed_indexes:
    print(f"Deployed Index ID: {deployed_index.id}")
    print(f"Display Name: {deployed_index.display_name}")
    print(f"Index Resource: {deployed_index.index}")

Deployed Index ID: index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe
Display Name: deployed-alpha-index
Index Resource: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296

In [47]:
import numpy as np

# Asegurar tipo float32
query_embedding = np.array(query_embedding, dtype=np.float32).tolist()
print(f"Dimensión del embedding consultado: {len(query_embedding)}, tipo: {type(query_embedding[0])}")

Dimensión del embedding consultado: 768, tipo: <class 'float'>

In [50]:
from google.cloud import aiplatform

aiplatform.init(project="bubbo-dfba0", location="europe-southwest1")

# Cargar el índice por su nombre
index = aiplatform.MatchingEngineIndex(index_name="projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296")
index_resource = index.gca_resource

print(f"Estado del índice: {index_resource.state}")
if hasattr(index_resource, 'index_stats'):
    print(f"Index stats: {index_resource.index_stats}")
else:
    print("Index stats no disponibles")

AttributeError: Unknown field for Index: state

In [51]:
endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name="5785049643217846272")
for deployed_index in endpoint.deployed_indexes:
    print(f"Deployed Index ID: {deployed_index.id}")
    print(f"Index resource name: {deployed_index.index}")
    print(f"Number of neighbors retrieved per query: {deployed_index.nearest_neighbor_search_config.tree_ah_config.approximate_neighbors_count}")

Deployed Index ID: index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe
Index resource name: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296

AttributeError: Unknown field for DeployedIndex: nearest_neighbor_search_config

In [52]:
from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket("embeddings_new_bucket")
blobs = bucket.list_blobs(prefix="embeddings/index_data/")

print("Archivos en embeddings/index_data/:")
for blob in blobs:
    print(f"- {blob.name} ({blob.size / 1024:.1f} KB)")

Archivos en embeddings/index_data/:
- embeddings/index_data/all_embeddings.jsonl (7388135.2 KB)

In [54]:
from google.protobuf.json_format import MessageToDict

index = aiplatform.MatchingEngineIndex(index_name="projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296")
index_dict = MessageToDict(index._gca_resource._pb)

import pprint
pprint.pprint(index_dict)

{'createTime': '2025-05-02T20:27:34.670598Z',
 'deployedIndexes': [{'deployedIndexId': 'index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe',
                      'displayName': 'deployed-alpha-index',
                      'indexEndpoint': 'projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272'}],
 'displayName': 'index-for-alpha-recs-movies-and-tv-shows-tree-ah-europe-southwest1',
 'encryptionSpec': {},
 'etag': 'AMEw9yPgMHEIJP-LKqKKBuTelE6mipXSXSLMy7e3BE8VZrO4GJbeV3MSe5krGvzaRVRz',
 'indexStats': {'shardsCount': 1},
 'indexUpdateMethod': 'STREAM_UPDATE',
 'metadata': {'config': {'algorithmConfig': {'treeAhConfig': {}},
                         'approximateNeighborsCount': 250.0,
                         'dimensions': 768.0,
                         'distanceMeasureType': 'COSINE_DISTANCE',
                         'shardSize': 'SHARD_SIZE_MEDIUM'}},
 'metadataSchemaUri': 'gs://google-cloud-aiplatform/schema/matchingengine/metadata/nearest_neighbor_search_1.0.0.yaml',
 'name': 'projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296',
 'updateTime': '2025-05-02T20:28:05.978402Z'}

In [55]:
index_endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name="5785049643217846272")
deployed_index = index_endpoint.deployed_indexes[0]

print(f"Deployed index ID: {deployed_index.id}")
print(f"Index resource: {deployed_index.index}")

# Obtener estadísticas del índice
index = aiplatform.MatchingEngineIndex(index_name=deployed_index.index)
stats = index._gca_resource.index_stats

if stats and hasattr(stats, "vectors_count"):
    print(f"🔍 Vectores cargados: {stats.vectors_count}")
else:
    print("⚠️ No se encontró información sobre la cantidad de vectores cargados.")

Deployed index ID: index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe
Index resource: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296
🔍 Vectores cargados: 0

In [56]:
from google.cloud import storage

# Verificar si el archivo está accesible
client = storage.Client()
bucket_name = "embeddings_new_bucket"
blob_path = "embeddings/index_data/all_embeddings.jsonl"

bucket = client.bucket(bucket_name)
blob = bucket.blob(blob_path)

if blob.exists():
    print(f"✔️ El archivo {blob_path} está disponible.")
else:
    print(f"⚠️ El archivo {blob_path} no se encontró en el bucket.")

✔️ El archivo embeddings/index_data/all_embeddings.jsonl está disponible.

In [57]:
import os
import time
import re
from google.cloud import aiplatform
from google.cloud import storage

# === CONFIGURACIÓN ===
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

PROJECT = "bubbo-dfba0"
LOCATION = "europe-southwest1"
STAGING_BUCKET = "gs://embeddings_new_bucket"
INDEX_NAME = "alpha_recs_movies_tv_tree_ah_eu_sw1"  # nuevo nombre corto
INDEX_URI = "gs://embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl"
DIMENSIONS = 768
ENDPOINT_ID = "projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272"
EXPECTED_COUNT = 440_000

# === INICIAR PLATAFORMA ===
aiplatform.init(project=PROJECT, location=LOCATION, staging_bucket=STAGING_BUCKET)

# Resumen de ejecución
execution_report = {
    "index_name": INDEX_NAME,
    "status": "started",
    "steps": []
}

# === VALIDAR: CANTIDAD DE EMBEDDINGS ===
def count_jsonl_lines(bucket_name, blob_path):
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    with blob.open("rt") as f:
        return sum(1 for _ in f)

bucket_name = "embeddings_new_bucket"
blob_path = "embeddings/index_data/all_embeddings.jsonl"
line_count = count_jsonl_lines(bucket_name, blob_path)
execution_report["steps"].append(f"Embeddings detectados en JSONL: {line_count}")
print(f"📦 Embeddings detectados en JSONL: {line_count}")

if line_count < EXPECTED_COUNT:
    error_msg = f"❌ Archivo incompleto: {line_count} embeddings, se esperaban al menos {EXPECTED_COUNT}."
    execution_report["status"] = "failed"
    execution_report["steps"].append(error_msg)
    raise ValueError(error_msg)

# === ELIMINAR ÍNDICE EXISTENTE ===
print("🔍 Verificando índices existentes...")
execution_report["steps"].append("Verificando índices existentes...")
existing_indexes = aiplatform.MatchingEngineIndex.list(filter=f'display_name="{INDEX_NAME}"')
for existing in existing_indexes:
    print(f"🗑️ Eliminando índice anterior: {existing.resource_name}")
    execution_report["steps"].append(f"Eliminando índice anterior: {existing.resource_name}")
    existing.delete()
    existing.wait()

# === CREAR NUEVO ÍNDICE ===
print("🛠️ Creando nuevo índice...")
execution_report["steps"].append("Creando nuevo índice...")
start = time.time()
index = aiplatform.MatchingEngineIndex.create_tree_ah_index(
    display_name=INDEX_NAME,
    contents_delta_uri=INDEX_URI,
    dimensions=DIMENSIONS,
    approximate_neighbors_count=250,
    distance_measure_type="COSINE_DISTANCE",
    index_update_method="STREAM_UPDATE"
)
index.wait()
elapsed = time.time() - start
execution_report["steps"].append(f"✅ Índice creado: {index.resource_name} en {elapsed / 60:.1f} minutos.")
print(f"✅ Índice creado en {elapsed / 60:.1f} minutos: {index.resource_name}")

# === DESPLEGAR EN ENDPOINT EXISTENTE ===
print("🚚 Desplegando índice en endpoint existente...")
execution_report["steps"].append(f"Desplegando índice en endpoint: {ENDPOINT_ID}")
endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name=ENDPOINT_ID)

deployed_index_id = re.sub(r'[^a-zA-Z0-9_]', '_', INDEX_NAME)
if not deployed_index_id[0].isalpha():
    deployed_index_id = f"a_{deployed_index_id}"
deployed_index_id = deployed_index_id[:63]

# Eliminar cualquier índice ya desplegado con el mismo ID
for d in endpoint.deployed_indexes:
    if d.id == deployed_index_id:
        print(f"🔄 Eliminando despliegue previo con ID: {deployed_index_id}")
        execution_report["steps"].append(f"🔄 Eliminando despliegue previo con ID: {deployed_index_id}")
        endpoint.undeploy_index(deployed_index_id=d.id)
        time.sleep(5)

endpoint.deploy_index(
    index=index,
    deployed_index_id=deployed_index_id,
    display_name="deployed-alpha-index",
)
execution_report["steps"].append(f"🚀 Índice desplegado exitosamente con ID: {deployed_index_id}")
print(f"🚀 Índice desplegado exitosamente con ID: {deployed_index_id}")

# Actualizar el estado final
execution_report["status"] = "success"
execution_report["steps"].append("Ejecución completada con éxito.")

# Mostrar el reporte final
print("\n🔄 Reporte de ejecución:")
for step in execution_report["steps"]:
    print(step)

# El reporte final está en la variable `execution_report`

📦 Embeddings detectados en JSONL: 444746
🔍 Verificando índices existentes...
🛠️ Creando nuevo índice...
Creating MatchingEngineIndex
Create MatchingEngineIndex backing LRO: projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464/operations/768981939792117760
MatchingEngineIndex created. Resource name: projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464
To use this MatchingEngineIndex in another session:
index = aiplatform.MatchingEngineIndex('projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464')
✅ Índice creado en 0.7 minutos: projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464
🚚 Desplegando índice en endpoint existente...
Deploying index MatchingEngineIndexEndpoint index_endpoint: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
Deploy index MatchingEngineIndexEndpoint index_endpoint backing LRO: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272/operations/4074624066282061824
MatchingEngineIndexEndpoint index_endpoint Deployed index. Resource name: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
🚀 Índice desplegado exitosamente con ID: alpha_recs_movies_tv_tree_ah_eu_sw1

🔄 Reporte de ejecución:
Embeddings detectados en JSONL: 444746
Verificando índices existentes...
Creando nuevo índice...
✅ Índice creado: projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464 en 0.7 minutos.
Desplegando índice en endpoint: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
🚀 Índice desplegado exitosamente con ID: alpha_recs_movies_tv_tree_ah_eu_sw1
Ejecución completada con éxito.

In [59]:
# Obtener detalles del índice
index = aiplatform.MatchingEngineIndex('projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464')

# Obtener el recurso del índice
index_resource = index.gca_resource

# Imprimir detalles del recurso
print(f"Detalles del índice: {index_resource}")

Detalles del índice: name: "projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464"
display_name: "alpha_recs_movies_tv_tree_ah_eu_sw1"
metadata_schema_uri: "gs://google-cloud-aiplatform/schema/matchingengine/metadata/nearest_neighbor_search_1.0.0.yaml"
metadata {
  struct_value {
    fields {
      key: "config"
      value {
        struct_value {
          fields {
            key: "shardSize"
            value {
              string_value: "SHARD_SIZE_MEDIUM"
            }
          }
          fields {
            key: "distanceMeasureType"
            value {
              string_value: "COSINE_DISTANCE"
            }
          }
          fields {
            key: "dimensions"
            value {
              number_value: 768
            }
          }
          fields {
            key: "approximateNeighborsCount"
            value {
              number_value: 250
            }
          }
          fields {
            key: "algorithmConfig"
            value {
              struct_value {
                fields {
                  key: "treeAhConfig"
                  value {
                    struct_value {
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
deployed_indexes {
  index_endpoint: "projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272"
  deployed_index_id: "alpha_recs_movies_tv_tree_ah_eu_sw1"
  display_name: "deployed-alpha-index"
}
etag: "AMEw9yNRcc1QN8pB3m94sxjdvdOvYDsBcRrdbRNOfPzQenX6MwjRmf9D-VSdSDnoNoPj"
create_time {
  seconds: 1746467299
  nanos: 905526000
}
update_time {
  seconds: 1746467332
  nanos: 866012000
}
index_stats {
  shards_count: 1
}
index_update_method: STREAM_UPDATE
encryption_spec {
}

In [60]:
from google.cloud import aiplatform

# Usar el nombre del endpoint correcto y el ID de índice desplegado
index_endpoint_name = "5785049643217846272"  # Este es el endpoint ya existente que confirmamos
index_resource_name = "projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464"  # El nuevo índice creado

# Obtener el endpoint y el índice desplegado
index_endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name=index_endpoint_name)
deployed_index = index_endpoint.deployed_indexes[0]

# Mostrar información del índice desplegado
print(f"Deployed index ID: {deployed_index.id}")
print(f"Index resource: {deployed_index.index}")

# Obtener estadísticas del índice
index = aiplatform.MatchingEngineIndex(index_name=index_resource_name)
index_resource = index.gca_resource
stats = index_resource.index_stats

# Verificar si hay estadísticas disponibles y mostrar la cantidad de vectores
if stats and hasattr(stats, "vectors_count"):
    print(f"🔍 Vectores cargados: {stats.vectors_count}")
else:
    print("⚠️ No se encontró información sobre la cantidad de vectores cargados.")

Deployed index ID: index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe
Index resource: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296
🔍 Vectores cargados: 0

In [62]:
# Obtener recurso del índice y estado
index_resource = index.gca_resource
if hasattr(index_resource, "index_stats"):
    print(f"Estadísticas del índice: {index_resource.index_stats}")
else:
    print("⚠️ No se encontraron estadísticas del índice.")

Estadísticas del índice: shards_count: 1

In [83]:
from google.cloud import aiplatform

aiplatform.init(project="bubbo-dfba0", location="europe-southwest1")

# Obtener todos los endpoints de Matching Engine
endpoints = aiplatform.MatchingEngineIndexEndpoint.list()

for endpoint in endpoints:
    print(f"\n🛰️ Endpoint: {endpoint.resource_name}")
    for deployed_index in endpoint.deployed_indexes:
        print(f"   ↳ Deployed Index ID: {deployed_index.id}")
        print(f"   ↳ Index Resource: {deployed_index.index}")

🛰️ Endpoint: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
   ↳ Deployed Index ID: index_for_alpha_recs_movies_and_tv_shows_tree_ah_europe_southwe
   ↳ Index Resource: projects/75629471929/locations/europe-southwest1/indexes/1087302650661175296
   ↳ Deployed Index ID: alpha_recs_movies_tv_tree_ah_eu_sw1
   ↳ Index Resource: projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464

In [85]:
import json
from google.cloud import storage

# Configurá el path a tus credenciales si hace falta
# os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "path/to/tu-clave.json"

# Parámetros
BUCKET_NAME = "embeddings_new_bucket"
BLOB_PATH = "embeddings/index_data/all_embeddings.jsonl"
EXPECTED_DIM = 768
MAX_LINES = 10000  # Líneas a revisar

# Cliente de GCS
client = storage.Client()
bucket = client.bucket(BUCKET_NAME)
blob = bucket.blob(BLOB_PATH)

# Contadores
valid_lines = 0
invalid_lines = 0
invalid_details = []  # Para almacenar detalles de las líneas inválidas

# Validación
with blob.open("rt") as f:
    for i, line in enumerate(f):
        line_errors = []
        try:
            data = json.loads(line)
        except json.JSONDecodeError as e:
            line_errors.append(f"JSON inválido ({e})")
        
        if "id" not in data or not isinstance(data["id"], str):
            line_errors.append("Falta 'id' o no es un string")
        
        if "embedding" not in data:
            line_errors.append("Falta campo 'embedding'")
        elif not isinstance(data["embedding"], list):
            line_errors.append("'embedding' no es una lista")
        elif len(data["embedding"]) != EXPECTED_DIM:
            line_errors.append(f"Dimensión incorrecta ({len(data['embedding'])})")
        elif not all(isinstance(x, (int, float)) for x in data["embedding"]):
            line_errors.append("La lista contiene valores no numéricos")

        if line_errors:
            invalid_lines += 1
            invalid_details.append({"line": i + 1, "errors": line_errors})
        else:
            valid_lines += 1

        # Limitar a las primeras MAX_LINES para evitar revisar todo el archivo
        if i + 1 >= MAX_LINES:
            break

# Resumen
print(f"\n✅ Resumen de la validación:")
print(f"Total de líneas revisadas: {valid_lines + invalid_lines}")
print(f"Líneas válidas: {valid_lines}")
print(f"Líneas inválidas: {invalid_lines}\n")

if invalid_lines > 0:
    print(f"\n❌ Detalles de las líneas inválidas:")
    for detail in invalid_details:
        print(f"Línea {detail['line']} - Errores: {', '.join(detail['errors'])}")
else:
    print("🎉 ¡Todo está bien! No se encontraron líneas inválidas.")

print("\n✅ Validación completada.")

✅ Resumen de la validación:
Total de líneas revisadas: 10000
Líneas válidas: 10000
Líneas inválidas: 0

🎉 ¡Todo está bien! No se encontraron líneas inválidas.

✅ Validación completada.

In [87]:
import json
import numpy as np
from google.cloud import storage

# Configuramos los parámetros
BUCKET_NAME = "embeddings_new_bucket"
BLOB_PATH = "embeddings/index_data/all_embeddings.jsonl"
EXPECTED_DIM = 768  # Debe ser la dimensión correcta de los embeddings

# Cliente de GCS
client = storage.Client()
bucket = client.bucket(BUCKET_NAME)
blob = bucket.blob(BLOB_PATH)

# Función para comprobar si los valores son válidos (sin NaNs ni Inf)
def is_valid_vector(embedding):
    try:
        # Comprobar que todos los elementos sean números
        embedding_array = np.array(embedding)
        
        # Verificar que la dimensión sea la correcta y que no haya NaNs ni Infs
        if len(embedding_array) != EXPECTED_DIM:
            return False
        if np.any(np.isnan(embedding_array)) or np.any(np.isinf(embedding_array)):
            return False
        return True
    except Exception as e:
        return False

# Función para verificar el formato correcto (id y embedding)
def is_valid_format(data):
    return isinstance(data, dict) and "id" in data and "embedding" in data and isinstance(data["embedding"], list)

# Comprobación de cada línea
valid_lines = 0
invalid_lines = 0
invalid_format_lines = 0
invalid_indices = []

with blob.open("rt") as f:
    for i, line in enumerate(f):
        try:
            data = json.loads(line)
        except json.JSONDecodeError as e:
            invalid_lines += 1
            invalid_indices.append(i+1)
            continue

        # Verificar formato correcto
        if not is_valid_format(data):
            invalid_format_lines += 1
            invalid_indices.append(i+1)
            continue
        
        embedding = data.get("embedding")
        if embedding and is_valid_vector(embedding):
            valid_lines += 1
        else:
            invalid_lines += 1
            invalid_indices.append(i+1)

        if (i + 1) % 1000 == 0:
            print(f"🔍 Revisadas {i + 1} líneas...")

# Resultado
print(f"\n✅ Resumen de la validación de vectores:")
print(f"Total de líneas revisadas: {i + 1}")
print(f"Líneas válidas: {valid_lines}")
print(f"Líneas inválidas: {invalid_lines}")
print(f"Líneas con formato incorrecto: {invalid_format_lines}")
if invalid_lines > 0:
    print(f"Líneas inválidas encontradas en las posiciones: {invalid_indices}")
else:
    print("🎉 ¡Todo está bien! No se encontraron vectores inválidos ni con formato incorrecto.")

print("\n✅ Validación completada.")

🔍 Revisadas 1000 líneas...
🔍 Revisadas 2000 líneas...
🔍 Revisadas 3000 líneas...
🔍 Revisadas 4000 líneas...
🔍 Revisadas 5000 líneas...
🔍 Revisadas 6000 líneas...
🔍 Revisadas 7000 líneas...
🔍 Revisadas 8000 líneas...
🔍 Revisadas 9000 líneas...
🔍 Revisadas 10000 líneas...
🔍 Revisadas 11000 líneas...
🔍 Revisadas 12000 líneas...
🔍 Revisadas 13000 líneas...
🔍 Revisadas 14000 líneas...
🔍 Revisadas 15000 líneas...
🔍 Revisadas 16000 líneas...
🔍 Revisadas 17000 líneas...
🔍 Revisadas 18000 líneas...
🔍 Revisadas 19000 líneas...
🔍 Revisadas 20000 líneas...
🔍 Revisadas 21000 líneas...
🔍 Revisadas 22000 líneas...
🔍 Revisadas 23000 líneas...
🔍 Revisadas 24000 líneas...
🔍 Revisadas 25000 líneas...
🔍 Revisadas 26000 líneas...
🔍 Revisadas 27000 líneas...
🔍 Revisadas 28000 líneas...
🔍 Revisadas 29000 líneas...
🔍 Revisadas 30000 líneas...
🔍 Revisadas 31000 líneas...
🔍 Revisadas 32000 líneas...
🔍 Revisadas 33000 líneas...
🔍 Revisadas 34000 líneas...
🔍 Revisadas 35000 líneas...
🔍 Revisadas 36000 líneas...
🔍 Revisadas 37000 líneas...
🔍 Revisadas 38000 líneas...
🔍 Revisadas 39000 líneas...
🔍 Revisadas 40000 líneas...
🔍 Revisadas 41000 líneas...
🔍 Revisadas 42000 líneas...
🔍 Revisadas 43000 líneas...
🔍 Revisadas 44000 líneas...
🔍 Revisadas 45000 líneas...
🔍 Revisadas 46000 líneas...
🔍 Revisadas 47000 líneas...
🔍 Revisadas 48000 líneas...
🔍 Revisadas 49000 líneas...
🔍 Revisadas 50000 líneas...
🔍 Revisadas 51000 líneas...
🔍 Revisadas 52000 líneas...
🔍 Revisadas 53000 líneas...
🔍 Revisadas 54000 líneas...
🔍 Revisadas 55000 líneas...
🔍 Revisadas 56000 líneas...
🔍 Revisadas 57000 líneas...
🔍 Revisadas 58000 líneas...
🔍 Revisadas 59000 líneas...
🔍 Revisadas 60000 líneas...
🔍 Revisadas 61000 líneas...
🔍 Revisadas 62000 líneas...
🔍 Revisadas 63000 líneas...
🔍 Revisadas 64000 líneas...
🔍 Revisadas 65000 líneas...
🔍 Revisadas 66000 líneas...
🔍 Revisadas 67000 líneas...
🔍 Revisadas 68000 líneas...
🔍 Revisadas 69000 líneas...
🔍 Revisadas 70000 líneas...
🔍 Revisadas 71000 líneas...
🔍 Revisadas 72000 líneas...
🔍 Revisadas 73000 líneas...
🔍 Revisadas 74000 líneas...
🔍 Revisadas 75000 líneas...
🔍 Revisadas 76000 líneas...
🔍 Revisadas 77000 líneas...
🔍 Revisadas 78000 líneas...
🔍 Revisadas 79000 líneas...
🔍 Revisadas 80000 líneas...
🔍 Revisadas 81000 líneas...
🔍 Revisadas 82000 líneas...
🔍 Revisadas 83000 líneas...
🔍 Revisadas 84000 líneas...
🔍 Revisadas 85000 líneas...
🔍 Revisadas 86000 líneas...
🔍 Revisadas 87000 líneas...
🔍 Revisadas 88000 líneas...
🔍 Revisadas 89000 líneas...
🔍 Revisadas 90000 líneas...
🔍 Revisadas 91000 líneas...
🔍 Revisadas 92000 líneas...
🔍 Revisadas 93000 líneas...
🔍 Revisadas 94000 líneas...
🔍 Revisadas 95000 líneas...
🔍 Revisadas 96000 líneas...
🔍 Revisadas 97000 líneas...
🔍 Revisadas 98000 líneas...
🔍 Revisadas 99000 líneas...
🔍 Revisadas 100000 líneas...
🔍 Revisadas 101000 líneas...
🔍 Revisadas 102000 líneas...
🔍 Revisadas 103000 líneas...
🔍 Revisadas 104000 líneas...
🔍 Revisadas 105000 líneas...
🔍 Revisadas 106000 líneas...
🔍 Revisadas 107000 líneas...
🔍 Revisadas 108000 líneas...
🔍 Revisadas 109000 líneas...
🔍 Revisadas 110000 líneas...
🔍 Revisadas 111000 líneas...
🔍 Revisadas 112000 líneas...
🔍 Revisadas 113000 líneas...
🔍 Revisadas 114000 líneas...
🔍 Revisadas 115000 líneas...
🔍 Revisadas 116000 líneas...
🔍 Revisadas 117000 líneas...
🔍 Revisadas 118000 líneas...
🔍 Revisadas 119000 líneas...
🔍 Revisadas 120000 líneas...
🔍 Revisadas 121000 líneas...
🔍 Revisadas 122000 líneas...
🔍 Revisadas 123000 líneas...
🔍 Revisadas 124000 líneas...
🔍 Revisadas 125000 líneas...
🔍 Revisadas 126000 líneas...
🔍 Revisadas 127000 líneas...
🔍 Revisadas 128000 líneas...
🔍 Revisadas 129000 líneas...
🔍 Revisadas 130000 líneas...
🔍 Revisadas 131000 líneas...
🔍 Revisadas 132000 líneas...
🔍 Revisadas 133000 líneas...
🔍 Revisadas 134000 líneas...
🔍 Revisadas 135000 líneas...
🔍 Revisadas 136000 líneas...
🔍 Revisadas 137000 líneas...
🔍 Revisadas 138000 líneas...
🔍 Revisadas 139000 líneas...
🔍 Revisadas 140000 líneas...
🔍 Revisadas 141000 líneas...
🔍 Revisadas 142000 líneas...
🔍 Revisadas 143000 líneas...
🔍 Revisadas 144000 líneas...
🔍 Revisadas 145000 líneas...
🔍 Revisadas 146000 líneas...
🔍 Revisadas 147000 líneas...
🔍 Revisadas 148000 líneas...
🔍 Revisadas 149000 líneas...
🔍 Revisadas 150000 líneas...
🔍 Revisadas 151000 líneas...
🔍 Revisadas 152000 líneas...
🔍 Revisadas 153000 líneas...
🔍 Revisadas 154000 líneas...
🔍 Revisadas 155000 líneas...
🔍 Revisadas 156000 líneas...
🔍 Revisadas 157000 líneas...
🔍 Revisadas 158000 líneas...
🔍 Revisadas 159000 líneas...
🔍 Revisadas 160000 líneas...
🔍 Revisadas 161000 líneas...
🔍 Revisadas 162000 líneas...
🔍 Revisadas 163000 líneas...
🔍 Revisadas 164000 líneas...
🔍 Revisadas 165000 líneas...
🔍 Revisadas 166000 líneas...
🔍 Revisadas 167000 líneas...
🔍 Revisadas 168000 líneas...
🔍 Revisadas 169000 líneas...
🔍 Revisadas 170000 líneas...
🔍 Revisadas 171000 líneas...
🔍 Revisadas 172000 líneas...
🔍 Revisadas 173000 líneas...
🔍 Revisadas 174000 líneas...
🔍 Revisadas 175000 líneas...
🔍 Revisadas 176000 líneas...
🔍 Revisadas 177000 líneas...
🔍 Revisadas 178000 líneas...
🔍 Revisadas 179000 líneas...
🔍 Revisadas 180000 líneas...
🔍 Revisadas 181000 líneas...
🔍 Revisadas 182000 líneas...
🔍 Revisadas 183000 líneas...
🔍 Revisadas 184000 líneas...
🔍 Revisadas 185000 líneas...
🔍 Revisadas 186000 líneas...
🔍 Revisadas 187000 líneas...
🔍 Revisadas 188000 líneas...
🔍 Revisadas 189000 líneas...
🔍 Revisadas 190000 líneas...
🔍 Revisadas 191000 líneas...
🔍 Revisadas 192000 líneas...
🔍 Revisadas 193000 líneas...
🔍 Revisadas 194000 líneas...
🔍 Revisadas 195000 líneas...
🔍 Revisadas 196000 líneas...
🔍 Revisadas 197000 líneas...
🔍 Revisadas 198000 líneas...
🔍 Revisadas 199000 líneas...
🔍 Revisadas 200000 líneas...
🔍 Revisadas 201000 líneas...
🔍 Revisadas 202000 líneas...
🔍 Revisadas 203000 líneas...
🔍 Revisadas 204000 líneas...
🔍 Revisadas 205000 líneas...
🔍 Revisadas 206000 líneas...
🔍 Revisadas 207000 líneas...
🔍 Revisadas 208000 líneas...
🔍 Revisadas 209000 líneas...
🔍 Revisadas 210000 líneas...
🔍 Revisadas 211000 líneas...
🔍 Revisadas 212000 líneas...
🔍 Revisadas 213000 líneas...
🔍 Revisadas 214000 líneas...
🔍 Revisadas 215000 líneas...
🔍 Revisadas 216000 líneas...
🔍 Revisadas 217000 líneas...
🔍 Revisadas 218000 líneas...
🔍 Revisadas 219000 líneas...
🔍 Revisadas 220000 líneas...
🔍 Revisadas 221000 líneas...
🔍 Revisadas 222000 líneas...
🔍 Revisadas 223000 líneas...
🔍 Revisadas 224000 líneas...
🔍 Revisadas 225000 líneas...
🔍 Revisadas 226000 líneas...
🔍 Revisadas 227000 líneas...
🔍 Revisadas 228000 líneas...
🔍 Revisadas 229000 líneas...
🔍 Revisadas 230000 líneas...
🔍 Revisadas 231000 líneas...
🔍 Revisadas 232000 líneas...
🔍 Revisadas 233000 líneas...
🔍 Revisadas 234000 líneas...
🔍 Revisadas 235000 líneas...
🔍 Revisadas 236000 líneas...
🔍 Revisadas 237000 líneas...
🔍 Revisadas 238000 líneas...
🔍 Revisadas 239000 líneas...
🔍 Revisadas 240000 líneas...
🔍 Revisadas 241000 líneas...
🔍 Revisadas 242000 líneas...
🔍 Revisadas 243000 líneas...
🔍 Revisadas 244000 líneas...
🔍 Revisadas 245000 líneas...
🔍 Revisadas 246000 líneas...
🔍 Revisadas 247000 líneas...
🔍 Revisadas 248000 líneas...
🔍 Revisadas 249000 líneas...
🔍 Revisadas 250000 líneas...
🔍 Revisadas 251000 líneas...
🔍 Revisadas 252000 líneas...
🔍 Revisadas 253000 líneas...
🔍 Revisadas 254000 líneas...
🔍 Revisadas 255000 líneas...
🔍 Revisadas 256000 líneas...
🔍 Revisadas 257000 líneas...
🔍 Revisadas 258000 líneas...
🔍 Revisadas 259000 líneas...
🔍 Revisadas 260000 líneas...
🔍 Revisadas 261000 líneas...
🔍 Revisadas 262000 líneas...
🔍 Revisadas 263000 líneas...
🔍 Revisadas 264000 líneas...
🔍 Revisadas 265000 líneas...
🔍 Revisadas 266000 líneas...
🔍 Revisadas 267000 líneas...
🔍 Revisadas 268000 líneas...
🔍 Revisadas 269000 líneas...
🔍 Revisadas 270000 líneas...
🔍 Revisadas 271000 líneas...
🔍 Revisadas 272000 líneas...
🔍 Revisadas 273000 líneas...
🔍 Revisadas 274000 líneas...
🔍 Revisadas 275000 líneas...
🔍 Revisadas 276000 líneas...
🔍 Revisadas 277000 líneas...
🔍 Revisadas 278000 líneas...
🔍 Revisadas 279000 líneas...
🔍 Revisadas 280000 líneas...
🔍 Revisadas 281000 líneas...
🔍 Revisadas 282000 líneas...
🔍 Revisadas 283000 líneas...
🔍 Revisadas 284000 líneas...
🔍 Revisadas 285000 líneas...
🔍 Revisadas 286000 líneas...
🔍 Revisadas 287000 líneas...
🔍 Revisadas 288000 líneas...
🔍 Revisadas 289000 líneas...
🔍 Revisadas 290000 líneas...
🔍 Revisadas 291000 líneas...
🔍 Revisadas 292000 líneas...
🔍 Revisadas 293000 líneas...
🔍 Revisadas 294000 líneas...
🔍 Revisadas 295000 líneas...
🔍 Revisadas 296000 líneas...
🔍 Revisadas 297000 líneas...
🔍 Revisadas 298000 líneas...
🔍 Revisadas 299000 líneas...
🔍 Revisadas 300000 líneas...
🔍 Revisadas 301000 líneas...
🔍 Revisadas 302000 líneas...
🔍 Revisadas 303000 líneas...
🔍 Revisadas 304000 líneas...
🔍 Revisadas 305000 líneas...
🔍 Revisadas 306000 líneas...
🔍 Revisadas 307000 líneas...
🔍 Revisadas 308000 líneas...
🔍 Revisadas 309000 líneas...
🔍 Revisadas 310000 líneas...
🔍 Revisadas 311000 líneas...
🔍 Revisadas 312000 líneas...
🔍 Revisadas 313000 líneas...
🔍 Revisadas 314000 líneas...
🔍 Revisadas 315000 líneas...
🔍 Revisadas 316000 líneas...
🔍 Revisadas 317000 líneas...
🔍 Revisadas 318000 líneas...
🔍 Revisadas 319000 líneas...
🔍 Revisadas 320000 líneas...
🔍 Revisadas 321000 líneas...
🔍 Revisadas 322000 líneas...
🔍 Revisadas 323000 líneas...
🔍 Revisadas 324000 líneas...
🔍 Revisadas 325000 líneas...
🔍 Revisadas 326000 líneas...
🔍 Revisadas 327000 líneas...
🔍 Revisadas 328000 líneas...
🔍 Revisadas 329000 líneas...
🔍 Revisadas 330000 líneas...
🔍 Revisadas 331000 líneas...
🔍 Revisadas 332000 líneas...
🔍 Revisadas 333000 líneas...
🔍 Revisadas 334000 líneas...
🔍 Revisadas 335000 líneas...
🔍 Revisadas 336000 líneas...
🔍 Revisadas 337000 líneas...
🔍 Revisadas 338000 líneas...
🔍 Revisadas 339000 líneas...
🔍 Revisadas 340000 líneas...
🔍 Revisadas 341000 líneas...
🔍 Revisadas 342000 líneas...
🔍 Revisadas 343000 líneas...
🔍 Revisadas 344000 líneas...
🔍 Revisadas 345000 líneas...
🔍 Revisadas 346000 líneas...
🔍 Revisadas 347000 líneas...
🔍 Revisadas 348000 líneas...
🔍 Revisadas 349000 líneas...
🔍 Revisadas 350000 líneas...
🔍 Revisadas 351000 líneas...
🔍 Revisadas 352000 líneas...
🔍 Revisadas 353000 líneas...
🔍 Revisadas 354000 líneas...
🔍 Revisadas 355000 líneas...
🔍 Revisadas 356000 líneas...
🔍 Revisadas 357000 líneas...
🔍 Revisadas 358000 líneas...
🔍 Revisadas 359000 líneas...
🔍 Revisadas 360000 líneas...
🔍 Revisadas 361000 líneas...
🔍 Revisadas 362000 líneas...
🔍 Revisadas 363000 líneas...
🔍 Revisadas 364000 líneas...
🔍 Revisadas 365000 líneas...
🔍 Revisadas 366000 líneas...
🔍 Revisadas 367000 líneas...
🔍 Revisadas 368000 líneas...
🔍 Revisadas 369000 líneas...
🔍 Revisadas 370000 líneas...
🔍 Revisadas 371000 líneas...
🔍 Revisadas 372000 líneas...
🔍 Revisadas 373000 líneas...
🔍 Revisadas 374000 líneas...
🔍 Revisadas 375000 líneas...
🔍 Revisadas 376000 líneas...
🔍 Revisadas 377000 líneas...
🔍 Revisadas 378000 líneas...
🔍 Revisadas 379000 líneas...
🔍 Revisadas 380000 líneas...
🔍 Revisadas 381000 líneas...
🔍 Revisadas 382000 líneas...
🔍 Revisadas 383000 líneas...
🔍 Revisadas 384000 líneas...
🔍 Revisadas 385000 líneas...
🔍 Revisadas 386000 líneas...
🔍 Revisadas 387000 líneas...
🔍 Revisadas 388000 líneas...
🔍 Revisadas 389000 líneas...
🔍 Revisadas 390000 líneas...
🔍 Revisadas 391000 líneas...
🔍 Revisadas 392000 líneas...
🔍 Revisadas 393000 líneas...
🔍 Revisadas 394000 líneas...
🔍 Revisadas 395000 líneas...
🔍 Revisadas 396000 líneas...
🔍 Revisadas 397000 líneas...
🔍 Revisadas 398000 líneas...
🔍 Revisadas 399000 líneas...
🔍 Revisadas 400000 líneas...
🔍 Revisadas 401000 líneas...
🔍 Revisadas 402000 líneas...
🔍 Revisadas 403000 líneas...
🔍 Revisadas 404000 líneas...
🔍 Revisadas 405000 líneas...
🔍 Revisadas 406000 líneas...
🔍 Revisadas 407000 líneas...
🔍 Revisadas 408000 líneas...
🔍 Revisadas 409000 líneas...
🔍 Revisadas 410000 líneas...
🔍 Revisadas 411000 líneas...
🔍 Revisadas 412000 líneas...
🔍 Revisadas 413000 líneas...
🔍 Revisadas 414000 líneas...
🔍 Revisadas 415000 líneas...
🔍 Revisadas 416000 líneas...
🔍 Revisadas 417000 líneas...
🔍 Revisadas 418000 líneas...
🔍 Revisadas 419000 líneas...
🔍 Revisadas 420000 líneas...
🔍 Revisadas 421000 líneas...
🔍 Revisadas 422000 líneas...
🔍 Revisadas 423000 líneas...
🔍 Revisadas 424000 líneas...
🔍 Revisadas 425000 líneas...
🔍 Revisadas 426000 líneas...
🔍 Revisadas 427000 líneas...
🔍 Revisadas 428000 líneas...
🔍 Revisadas 429000 líneas...
🔍 Revisadas 430000 líneas...
🔍 Revisadas 431000 líneas...
🔍 Revisadas 432000 líneas...
🔍 Revisadas 433000 líneas...
🔍 Revisadas 434000 líneas...
🔍 Revisadas 435000 líneas...
🔍 Revisadas 436000 líneas...
🔍 Revisadas 437000 líneas...
🔍 Revisadas 438000 líneas...
🔍 Revisadas 439000 líneas...
🔍 Revisadas 440000 líneas...
🔍 Revisadas 441000 líneas...
🔍 Revisadas 442000 líneas...
🔍 Revisadas 443000 líneas...
🔍 Revisadas 444000 líneas...

✅ Resumen de la validación de vectores:
Total de líneas revisadas: 444746
Líneas válidas: 444746
Líneas inválidas: 0
Líneas con formato incorrecto: 0
🎉 ¡Todo está bien! No se encontraron vectores inválidos ni con formato incorrecto.

✅ Validación completada.

In [88]:
import os
import time
import re
from google.cloud import aiplatform
from google.cloud import storage

# === CONFIGURACIÓN ===
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

PROJECT = "bubbo-dfba0"
LOCATION = "europe-southwest1"
STAGING_BUCKET = "gs://embeddings_new_bucket"
INDEX_NAME = "alpha_recs_movies_tv_tree_ah_eu_sw1"  # nuevo nombre corto
INDEX_URI = "gs://embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl"
DIMENSIONS = 768
ENDPOINT_ID = "projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272"
EXPECTED_COUNT = 440_000

# === INICIAR PLATAFORMA ===
aiplatform.init(project=PROJECT, location=LOCATION, staging_bucket=STAGING_BUCKET)

# Resumen de ejecución
execution_report = {
    "index_name": INDEX_NAME,
    "status": "started",
    "steps": []
}

# === VALIDAR: CANTIDAD DE EMBEDDINGS ===
def count_jsonl_lines(bucket_name, blob_path):
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    with blob.open("rt") as f:
        return sum(1 for _ in f)

bucket_name = "embeddings_new_bucket"
blob_path = "embeddings/index_data/all_embeddings.jsonl"
line_count = count_jsonl_lines(bucket_name, blob_path)
execution_report["steps"].append(f"Embeddings detectados en JSONL: {line_count}")
print(f"📦 Embeddings detectados en JSONL: {line_count}")

if line_count < EXPECTED_COUNT:
    error_msg = f"❌ Archivo incompleto: {line_count} embeddings, se esperaban al menos {EXPECTED_COUNT}."
    execution_report["status"] = "failed"
    execution_report["steps"].append(error_msg)
    raise ValueError(error_msg)

# === ELIMINAR ÍNDICE EXISTENTE ===
print("🔍 Verificando índices existentes...")
execution_report["steps"].append("Verificando índices existentes...")
existing_indexes = aiplatform.MatchingEngineIndex.list(filter=f'display_name="{INDEX_NAME}"')
for existing in existing_indexes:
    print(f"🗑️ Eliminando índice anterior: {existing.resource_name}")
    execution_report["steps"].append(f"Eliminando índice anterior: {existing.resource_name}")
    existing.delete()
    existing.wait()

# === CREAR NUEVO ÍNDICE ===
print("🛠️ Creando nuevo índice...")
execution_report["steps"].append("Creando nuevo índice...")
start = time.time()
index = aiplatform.MatchingEngineIndex.create_tree_ah_index(
    display_name=INDEX_NAME,
    contents_delta_uri=INDEX_URI,
    dimensions=DIMENSIONS,
    approximate_neighbors_count=250,
    distance_measure_type="COSINE_DISTANCE",
    index_update_method="STREAM_UPDATE"
)
index.wait()
elapsed = time.time() - start
execution_report["steps"].append(f"✅ Índice creado: {index.resource_name} en {elapsed / 60:.1f} minutos.")
print(f"✅ Índice creado en {elapsed / 60:.1f} minutos: {index.resource_name}")

# === DESPLEGAR EN ENDPOINT EXISTENTE ===
print("🚚 Desplegando índice en endpoint existente...")
execution_report["steps"].append(f"Desplegando índice en endpoint: {ENDPOINT_ID}")
endpoint = aiplatform.MatchingEngineIndexEndpoint(index_endpoint_name=ENDPOINT_ID)

deployed_index_id = re.sub(r'[^a-zA-Z0-9_]', '_', INDEX_NAME)
if not deployed_index_id[0].isalpha():
    deployed_index_id = f"a_{deployed_index_id}"
deployed_index_id = deployed_index_id[:63]

# Eliminar cualquier índice ya desplegado con el mismo ID
for d in endpoint.deployed_indexes:
    if d.id == deployed_index_id:
        print(f"🔄 Eliminando despliegue previo con ID: {deployed_index_id}")
        execution_report["steps"].append(f"🔄 Eliminando despliegue previo con ID: {deployed_index_id}")
        endpoint.undeploy_index(deployed_index_id=d.id)
        time.sleep(5)

endpoint.deploy_index(
    index=index,
    deployed_index_id=deployed_index_id,
    display_name="deployed-alpha-index",
)
execution_report["steps"].append(f"🚀 Índice desplegado exitosamente con ID: {deployed_index_id}")
print(f"🚀 Índice desplegado exitosamente con ID: {deployed_index_id}")

# Actualizar el estado final
execution_report["status"] = "success"
execution_report["steps"].append("Ejecución completada con éxito.")

# Mostrar el reporte final
print("\n🔄 Reporte de ejecución:")
for step in execution_report["steps"]:
    print(step)

# El reporte final está en la variable `execution_report`

📦 Embeddings detectados en JSONL: 444746
🔍 Verificando índices existentes...
🗑️ Eliminando índice anterior: projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464
Deleting MatchingEngineIndex : projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464

FailedPrecondition: 400 The Index "projects/75629471929/locations/europe-southwest1/indexes/1988867001065406464" is deployed or being deployed at the following IndexEndpoint(s): projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272.

In [ ]:
Supuestamente el index quedó desplegandose

In [93]:
from google.cloud import aiplatform_v1

# Parámetros
project = "bubbo-dfba0"
location = "europe-southwest1"
index_id = "1988867001065406464"
index_name = f"projects/{project}/locations/{location}/indexes/{index_id}"

# Crear cliente en la región correcta
client_options = {"api_endpoint": f"{location}-aiplatform.googleapis.com"}
client = aiplatform_v1.IndexServiceClient(client_options=client_options)

# Obtener el índice
index = client.get_index(name=index_name)

# Mostrar estado de despliegue
if index.deployed_indexes:
    print("🚀 El índice está desplegado actualmente en:")
    for deployed in index.deployed_indexes:
        print(f"🛰️ IndexEndpoint: {deployed.index_endpoint}")
        print(f"📌 Deployed index ID: {deployed.deployed_index_id}")
else:
    print("📭 El índice no está desplegado en ningún endpoint.")

🚀 El índice está desplegado actualmente en:
🛰️ IndexEndpoint: projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272
📌 Deployed index ID: alpha_recs_movies_tv_tree_ah_eu_sw1

In [1]:
import os
import time
import re
from google.cloud import aiplatform
from google.cloud import storage

# === CONFIGURACIÓN ===
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

PROJECT = "bubbo-dfba0"
LOCATION = "europe-southwest1"
STAGING_BUCKET = "gs://embeddings_new_bucket"
INDEX_NAME = "alpha_recs_movies_tv_tree_ah_eu_sw1"
INDEX_URI = "gs://embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl"
DIMENSIONS = 768
ENDPOINT_ID = "projects/75629471929/locations/europe-southwest1/indexEndpoints/5785049643217846272"
EXPECTED_COUNT = 440_000

aiplatform.init(project=PROJECT, location=LOCATION, staging_bucket=STAGING_BUCKET)

execution_report = {
    "index_name": INDEX_NAME,
    "status": "started",
    "steps": []
}

# === VALIDAR CANTIDAD DE EMBEDDINGS ===
def count_jsonl_lines(bucket_name, blob_path):
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    with blob.open("rt") as f:
        return sum(1 for _ in f)

bucket_name = "embeddings_new_bucket"
blob_path = "embeddings/index_data/all_embeddings.jsonl"
line_count = count_jsonl_lines(bucket_name, blob_path)
execution_report["steps"].append(f"Embeddings detectados en JSONL: {line_count}")
print(f"Embeddings detectados en JSONL: {line_count}")

if line_count < EXPECTED_COUNT:
    error_msg = f"Archivo incompleto: {line_count} embeddings, se esperaban al menos {EXPECTED_COUNT}."
    execution_report["status"] = "failed"
    execution_report["steps"].append(error_msg)
    raise ValueError(error_msg)

NotFound: 404 GET https://storage.googleapis.com/download/storage/v1/b/embeddings_new_bucket/o/embeddings%2Findex_data%2Fall_embeddings.jsonl?alt=media: No such object: embeddings_new_bucket/embeddings/index_data/all_embeddings.jsonl: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

Deleting MatchingEngineIndex : projects/75629471929/locations/europe-southwest1/indexes/5502800610321235968
MatchingEngineIndex deleted. . Resource name: projects/75629471929/locations/europe-southwest1/indexes/5502800610321235968
Deleting MatchingEngineIndex resource: projects/75629471929/locations/europe-southwest1/indexes/5502800610321235968
Delete MatchingEngineIndex backing LRO: projects/75629471929/locations/europe-southwest1/indexes/5502800610321235968/operations/1466771601197367296
MatchingEngineIndex resource projects/75629471929/locations/europe-southwest1/indexes/5502800610321235968 deleted.
Creating MatchingEngineIndex
Create MatchingEngineIndex backing LRO: projects/75629471929/locations/europe-southwest1/indexes/1888098959402991616/operations/5718169649435115520
MatchingEngineIndex created. Resource name: projects/75629471929/locations/europe-southwest1/indexes/1888098959402991616
To use this MatchingEngineIndex in another session:
index = aiplatform.MatchingEngineIndex('projects/75629471929/locations/europe-southwest1/indexes/1888098959402991616')

AttributeError: 'MatchingEngineIndex' object has no attribute 'import_data'

In [2]:
from google.cloud import storage

def mostrar_lineas_iniciales(bucket_name, blob_path, n=3):
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)

    with blob.open("rt") as f:
        for i in range(n):
            line = f.readline()
            print(f"Línea {i+1}: {line.strip()}")

mostrar_lineas_iniciales(
    bucket_name="embeddings_new_bucket",
    blob_path="embeddings/index_data/all_embeddings.jsonl"
)

Línea 1: {"id": "100", "embedding": [-0.0009217166807502508, -0.027816399931907654, 0.042348381131887436, 0.06346812844276428, -0.030670298263430595, 0.027489224448800087, 0.0314815454185009, 0.010220708325505257, 0.023876585066318512, 0.011568091809749603, -0.015477398410439491, -0.009889459237456322, -0.022833410650491714, -0.030152367427945137, -0.020773785188794136, -0.0022359585855156183, -0.0069099594838917255, -0.06232764944434166, 0.008681670762598515, 0.056596413254737854, -0.08407587558031082, 0.039964426308870316, 0.06256385147571564, -0.04063131660223007, -0.04794082045555115, 0.03362669423222542, 0.029440846294164658, 0.0687476098537445, 0.054691143333911896, 0.08941961079835892, -0.0009745663264766335, -0.0016498188488185406, -0.0034676860086619854, 0.026875585317611694, -0.08315390348434448, 0.021503912284970284, -0.020892759785056114, -0.003366834716871381, 0.042940638959407806, 0.06786756217479706, 0.0030169568490236998, -0.10298775881528854, -0.018486252054572105, 0.044562604278326035, -0.005196806509047747, -0.05577559024095535, -0.019362399354577065, -0.04162418842315674, 0.03611278906464577, 0.03568345308303833, 0.036726582795381546, 0.08014840632677078, -0.020520318299531937, 0.0007595983915962279, 0.06492069363594055, -0.04751620814204216, -0.01529841497540474, -0.07752961665391922, -0.005159902852028608, 0.05850867182016373, 0.01156667247414589, 0.05011157691478729, 0.017201555892825127, 0.0026869773864746094, 0.012791942805051804, 0.0064340378157794476, 0.013495705090463161, -0.02993651293218136, 0.0013461426133289933, -0.016258910298347473, -0.059470467269420624, 0.030230263248085976, 0.0329284705221653, -0.04532448574900627, -0.030386846512556076, 0.058940112590789795, -0.03956226631999016, 0.04364325851202011, -0.041122764348983765, 0.027123263105750084, -0.014802413061261177, 0.06079861894249916, -0.014512622728943825, -0.013911280781030655, 0.10233696550130844, 0.0028332173824310303, -0.026674890890717506, -0.08882984519004822, 0.015233462676405907, -0.018080512061715126, 0.010874303989112377, -0.02919517084956169, -0.005165057256817818, -0.012813831679522991, -0.03137547895312309, -0.03126656264066696, 0.0336809866130352, 0.027993127703666687, -0.02338244952261448, -0.05042675510048866, 0.021559258922934532, -0.0075604566372931, -0.029185611754655838, -0.026718255132436752, 0.06175490841269493, -0.03266606107354164, 0.00013549851428251714, 0.04625151678919792, -0.024181609973311424, 0.050965603440999985, 0.01848941296339035, -0.0065552107989788055, -0.05680283531546593, 0.028222311288118362, -0.001927254954352975, 0.009210032410919666, -0.03809411823749542, 0.015946798026561737, -0.050424959510564804, -0.01533369068056345, 0.03970729932188988, 0.007282438222318888, 0.0026067099533975124, -0.010899808257818222, 0.02226468361914158, -0.04686913266777992, 0.01821923442184925, -0.04251403734087944, 0.024637481197714806, 0.0005009289598092437, 0.015452218241989613, 0.045840583741664886, 0.029497109353542328, -0.042612217366695404, -0.042879585176706314, 0.052066873759031296, 0.024753648787736893, -0.029821844771504402, -0.002698535332456231, 0.03233620896935463, -0.030500484630465508, 0.07611006498336792, 0.04427481070160866, -0.03318718820810318, -0.018006326630711555, -0.04223021864891052, -0.03480387479066849, 0.012991771101951599, 0.031224364414811134, 0.06584592163562775, -0.020902389660477638, -0.035066816955804825, -0.051799625158309937, -0.0013433978892862797, 0.023796143010258675, -0.017174959182739258, 0.018132219091057777, 0.0017778623150661588, 0.08183728903532028, -0.06674226373434067, -0.014023694209754467, -0.04052937030792236, -0.01885250024497509, 0.07497001439332962, 0.02109067142009735, -0.00688131945207715, 0.05884692817926407, 0.009445770643651485, 0.027886975556612015, -0.0508052334189415, -0.034446168690919876, 0.03466735780239105, -0.0010553045431151986, 0.017650559544563293, 0.017024265602231026, 0.0397530198097229, 0.02107134275138378, 0.03146655112504959, 0.019339151680469513, -0.049614857882261276, 0.03469376266002655, 0.022682195529341698, -0.028618114069104195, 0.06096822768449783, -0.08967741578817368, -0.003356422996148467, 0.011754038743674755, -0.0037724280264228582, 0.020850330591201782, 0.006134416908025742, -0.019993623718619347, -0.03395552933216095, 0.008478114381432533, -0.015956584364175797, -0.02770540490746498, 0.0745919719338417, 0.009194615297019482, -0.01881750114262104, -0.06566599756479263, -0.03591601550579071, -0.03827187046408653, -0.0664638951420784, 0.01352955773472786, -0.00865687895566225, -0.013701502233743668, 0.01210640650242567, 0.008359873667359352, 0.03845156356692314, 0.004356013610959053, 0.04912031814455986, 0.008728794753551483, -0.06607989221811295, -0.02665093168616295, 0.04367655888199806, -0.028053458780050278, -0.001378255314193666, 0.05190173164010048, -0.11265579611063004, -0.03252829611301422, -0.03075668029487133, -0.04016784206032753, -0.12758541107177734, -0.012522004544734955, 0.05183107778429985, -0.010352280922234058, -0.024503687396645546, -0.14181964099407196, 0.06097407266497612, -0.040963657200336456, 0.042191408574581146, 0.05985138565301895, 0.010707567445933819, -0.0538703016936779, -0.0289749875664711, -0.03046250529587269, -0.02143947221338749, 0.04782417044043541, -0.0870312973856926, 0.04627490043640137, -0.01659521460533142, -0.014466645196080208, 0.05352461710572243, 0.04014008119702339, 0.001876594964414835, -0.022489918395876884, -0.008442364633083344, 0.024627376347780228, 0.02278313599526882, 0.036717407405376434, 0.012897714041173458, 0.0016485040541738272, -0.026040423661470413, -0.024762358516454697, -0.041957419365644455, -0.049243517220020294, -0.03390040993690491, 0.020379818975925446, 0.03814476355910301, -0.04070119932293892, 0.04283924028277397, -0.01322109717875719, 0.043020449578762054, 0.0325288288295269, -0.021718762814998627, -0.00219733826816082, -0.0018562809564173222, -0.019643574953079224, -0.018180612474679947, -0.016655853018164635, 0.12390592694282532, 0.012447146698832512, 0.08859261870384216, 0.003834039904177189, -0.010705772787332535, -0.026941178366541862, 0.016808753833174706, -0.023756487295031548, 0.010189628228545189, -0.07019215822219849, 0.05037800967693329, -0.006690886337310076, -0.013998457230627537, -0.0004678698896896094, 0.04834148287773132, -0.017119184136390686, 0.020891888067126274, -0.05317467823624611, 0.021929433569312096, 0.024931270629167557, 0.028618885204195976, 0.010965608060359955, 0.008637670427560806, -0.011193189769983292, -0.002130002249032259, 0.014836996793746948, 0.06381525844335556, -0.04377171769738197, 0.009738837368786335, -0.022817222401499748, 0.016177216544747353, 0.062394190579652786, 0.0011421351227909327, -0.04605142027139664, 0.035928014665842056, 0.0010498873889446259, 0.032238781452178955, -0.006367798428982496, 0.005840805359184742, -0.0470854751765728, 0.012079047970473766, -0.01652444340288639, -0.002462429692968726, -0.005335427820682526, -0.025605520233511925, 0.016597429290413857, -0.004798599518835545, -0.017099810764193535, 0.02820957638323307, -0.014606938697397709, -0.0033952523954212666, -0.0257173590362072, 0.00299259927123785, -0.06720662117004395, 0.04293326660990715, 0.0014027045108377934, -0.005852058995515108, 0.022187432274222374, -0.00833679735660553, -0.023967646062374115, 0.05741932988166809, 0.015937361866235733, 0.009861520491540432, -0.014224857091903687, 0.007079530507326126, -0.015132513828575611, -0.012689391151070595, 0.060660477727651596, -0.018545910716056824, -0.004170672036707401, 0.08784876018762589, 0.014740211889147758, -0.008282092399895191, 0.0011443474795669317, -0.01933734118938446, 0.0037872607354074717, -0.032563310116529465, 0.05807223170995712, -0.04167341813445091, 0.05433082580566406, -0.014733350835740566, 0.007238670252263546, 0.040385983884334564, -0.008419683203101158, -0.08979463577270508, -0.0017884274711832404, 0.07238983362913132, 0.014221370220184326, 0.013908515684306622, -0.04955306276679039, 0.013516579754650593, 0.011410343460738659, -0.03534772992134094, 0.0007760213920846581, 0.00585224200040102, -0.009621932171285152, -0.003870810614898801, 0.0294390469789505, 0.00824795849621296, -0.04314916953444481, -0.04139428213238716, -0.0619315542280674, 0.05427068844437599, 0.014309081248939037, -0.027876948937773705, 0.03419267013669014, 0.026185061782598495, -0.006157968658953905, 0.004059723578393459, -0.025487765669822693, -0.0007510966970585287, 0.012131982482969761, 0.01838885433971882, 0.004199801478534937, 0.023860057815909386, -0.023773644119501114, -0.00044666099711321294, 0.04302719607949257, -0.061828579753637314, 0.014414941892027855, -0.011338042095303535, 0.035593852400779724, -0.031119629740715027, 0.008947611786425114, 0.019893789663910866, 0.0033858558163046837, 0.03883621469140053, -0.031109405681490898, -0.007827810011804104, -0.019891466945409775, 0.023330574855208397, 0.05795729160308838, -0.03222137317061424, -0.005029918160289526, -0.010957052931189537, -0.018676966428756714, 0.009247912093997002, -0.009849912486970425, 0.03652336820960045, -0.03782351687550545, -0.024964844807982445, 0.07339705526828766, -0.05546306073665619, -0.04576821252703667, -0.022262269631028175, -0.07900889217853546, -0.009290996007621288, -0.0014157341793179512, -0.005211435258388519, 0.06259189546108246, -0.03495035320520401, 0.01149998139590025, -0.04869115725159645, 0.025420021265745163, 0.02061697654426098, 0.020997297018766403, 0.01392487995326519, 0.06601167470216751, 0.011459769681096077, 0.0644971951842308, 0.05089813098311424, 0.023188509047031403, -0.00726065831258893, 0.0005174067919142544, -0.007138718850910664, 0.037492670118808746, -0.0066526769660413265, 0.009817284531891346, -0.041509900242090225, -0.04358835890889168, -0.003930828534066677, 0.007561029866337776, -0.04437461122870445, -0.0053267222829163074, -0.05802459269762039, -0.01410958357155323, -0.000517042470164597, 0.01812685839831829, 0.021740121766924858, 0.0049219075590372086, 0.05620935559272766, -0.0038143182173371315, -0.013157164677977562, 0.049148354679346085, 0.027664341032505035, 0.033590517938137054, 0.002431803848594427, -0.007216442842036486, 0.01921246200799942, 0.019745197147130966, 0.03395551070570946, 0.013996622525155544, -0.09791717678308487, 0.03244621679186821, -0.004360944498330355, 0.006118112243711948, 0.007711214944720268, 0.03310619667172432, -0.04610039293766022, -0.006557852029800415, -0.0029208713676780462, -0.020168403163552284, -0.016402577981352806, 0.020611507818102837, 0.032257139682769775, 0.021215014159679413, -0.006740160286426544, 0.01240026019513607, 0.07499559223651886, 0.026954710483551025, -0.04006706923246384, 0.004638905171304941, 0.0010122627718374133, 0.09215783327817917, 0.03234955295920372, -0.07004483044147491, -0.01034390926361084, 0.007473781704902649, -0.05814054235816002, -0.02226693369448185, 0.02521611750125885, -0.023186007514595985, 0.006680999882519245, -0.014957662671804428, -0.016951818019151688, -0.023879792541265488, -0.011090198531746864, 0.037156544625759125, 0.021576734259724617, 0.007327165454626083, -0.013056324794888496, 0.008392523974180222, -0.0313173346221447, -0.05991150438785553, 0.04444141313433647, 0.02033878304064274, -0.022826099768280983, -0.06005522236227989, -0.015444092452526093, 0.01543578039854765, -0.013917041942477226, 0.0032761823385953903, 0.0576808862388134, 0.016885260120034218, -0.03373374789953232, 0.018559593707323074, -0.01699254848062992, 0.02981572411954403, 0.008293963968753815, -0.009671326726675034, -0.008478367701172829, -0.046793725341558456, 0.10495970398187637, 0.016289589926600456, 0.02899232506752014, -0.020764393731951714, -0.022793427109718323, -0.005370027385652065, -0.05687502399086952, -0.021697593852877617, 0.010455457493662834, -0.030421309173107147, -0.029065024107694626, -0.04031390696763992, 0.030686650425195694, -0.009876763448119164, 0.06721555441617966, -0.05371361970901489, 0.048568520694971085, 0.021099867299199104, -0.03743133321404457, -0.0012799176620319486, -0.025244969874620438, -0.009059988893568516, -0.024912765249609947, 0.05236614868044853, 0.005713790189474821, -0.0061571476981043816, -0.022104425355792046, -0.04662907496094704, 0.05568473041057587, 0.01476152054965496, -0.0453607514500618, -0.023828774690628052, -0.019155994057655334, -0.02234015241265297, -0.06715407222509384, 0.0153026869520545, 0.01566164754331112, 0.038634058088064194, -0.012578827328979969, -0.04908118396997452, -0.0045433673076331615, 0.009043521247804165, -0.01420271024107933, 0.045082367956638336, -0.03142059966921806, 0.0019654836505651474, 0.02769157662987709, -0.041538842022418976, -0.004980428144335747, -0.10383102297782898, 0.004927793052047491, -0.013822969049215317, 0.020477546378970146, 0.04011811316013336, 0.016311971470713615, -0.04384680092334747, -0.01439171563833952, -0.03947516530752182, -0.014931161887943745, -0.003356784349307418, -0.05403757095336914, 0.07158895581960678, -0.0731104165315628, -0.017404986545443535, -0.038762643933296204, -0.015084169805049896, 0.025681525468826294, -0.020453117787837982, -0.05256364122033119, 0.014938692562282085, 0.015311780385673046, -0.01694396883249283, 0.05903052166104317, 0.0006505953497253358, -0.04628351703286171, 0.008903121575713158, 0.020999012514948845, 0.04112906754016876, -0.03888577222824097, 0.006931870710104704, 0.003713684156537056, 0.03922278806567192, -0.006921706255525351, 0.015252682380378246, 0.012399488128721714, 0.07252249121665955, -0.013342656195163727, -0.00174096436239779, -0.017307879403233528, -0.026519775390625, -0.00641930615529418, -0.035633642226457596, 0.0063712624832987785, 0.01633306033909321, -0.0665520653128624, -0.0008031941251829267, 0.009044324047863483, -0.02392493188381195, 0.03780888393521309, -0.038904499262571335, 0.014209412038326263, 0.04008980095386505, -0.001954104984179139, 0.04767129570245743, -0.024575814604759216, -0.036129165440797806, 0.0011571909999474883, -0.03563236445188522, -0.025437260046601295, 0.023959709331393242, 0.016507236286997795, 0.002823981223627925, -0.0706430971622467, 0.015400432050228119, 0.05975256860256195, 0.04126853868365288, 0.0272964034229517, 0.024054234847426414, 0.02307109162211418, 0.07174000144004822, 0.09567534923553467, 0.006418695207685232, 0.010161120444536209, 0.020141277462244034, 0.03624943271279335, 0.03666321560740471, 0.028910038992762566, 0.049928296357393265, -0.060796719044446945, -0.010952095501124859, 0.02233629673719406, 0.009665806777775288, -0.02752256952226162, 0.029436618089675903, 0.01548680942505598, 0.008681869134306908, -0.05344419181346893, -0.008353126235306263, 0.0020069133024662733, 0.04656665772199631, -0.038513969630002975, -0.03981463238596916, 0.03334716707468033, -0.001106441137380898, 0.0033315466716885567, 0.004331724718213081, -0.00686954939737916, -0.00884385034441948, -0.019680902361869812, -0.026334062218666077, 0.01683932915329933, -0.0070899538695812225, 0.008772997185587883, 0.0613924004137516, 0.055267658084630966, 0.01794305071234703, -0.02100851759314537, 0.08905358612537384, 0.04296343773603439, -0.028831951320171356, 0.04332193732261658, -0.0009546049986965954, -0.0032539968378841877, 0.03153934329748154, -0.029617514461278915, 0.0008956799283623695, 0.006790990009903908, -0.019577104598283768, -0.039136044681072235, -0.046653252094984055, -0.046407077461481094, 0.06149129569530487, -0.037748366594314575, 0.06492961943149567, -0.04789922758936882, 0.0153989652171731, -0.07126404345035553, 0.040268220007419586, -0.004550508689135313, -0.01878177933394909, -0.008173724636435509, -0.0561586394906044, 0.019185995683073997, 0.0005209207301959395, 0.007082770112901926, 0.007676938083022833, -0.046233586966991425, -0.005629011895507574, 0.01037396490573883, -0.02547580562531948, -0.03491021320223808, 0.009461063891649246, 0.04940834268927574, 0.0024844093713909388, 0.004990256391465664, 0.05721823498606682, -0.026086818426847458, 0.016294915229082108, 0.0413874015212059, 0.05507827177643776, 0.023656783625483513, 0.01929851435124874, 0.05706740543246269, 0.0317055881023407, 0.0423477478325367, 0.012984033674001694, -0.009340335614979267, -0.03611397743225098, 0.013398868031799793, -0.01343697588890791, -0.021457046270370483, -0.017227770760655403, 0.0013712483923882246, -0.033608391880989075, 0.04034360870718956, -0.014754705131053925, 0.009214619174599648, 0.039282169193029404, 0.015464452095329762, -0.014067542739212513, -0.006850104313343763, -0.028251511976122856, 0.042318619787693024, 0.0010159544181078672, -0.07910285890102386, -0.05739985778927803, -0.014814876019954681, -0.013562212698161602, -0.010929439216852188, -0.044873498380184174, -0.029638737440109253, 0.018473532050848007, 0.04032357782125473, -0.01731247454881668, 0.004057781305164099, -0.014460071921348572, -0.04746546223759651, -0.022014109417796135, -0.010901376605033875, -0.004708027932792902, -0.03543029725551605, 0.0077417166903615, -0.02296663261950016, 0.03288859501481056, 0.014409753493964672, -0.005033222958445549, 0.027523403987288475]}

In [ ]:
import json
from google.cloud import storage

def ver_estructura_json_gcs(bucket_name, blob_path, num_entradas=3):
    # Crear un cliente de Google Cloud Storage
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)

    # Abrir el archivo en el almacenamiento de GCS
    with blob.open("rt") as f:
        # Leer las primeras 'num_entradas' líneas del archivo JSONL
        for i in range(num_entradas):
            line = f.readline()
            if not line:
                break  # Si no hay más líneas, detener
            # Convertir la línea JSON en un objeto de Python
            json_data = json.loads(line.strip())
            print(f"Línea {i + 1}:")
            print(json_data)  # Mostrar el objeto JSON de la línea
            print("-" * 50)

# Llamar a la función pasando la ubicación del archivo en GCS
ver_estructura_json_gcs(
    bucket_name="embeddings_new_bucket",
    blob_path="embeddings/index_data/all_embeddings.jsonl",
    num_entradas=3
)

Línea 1:
{'id': '100', 'embedding': [-0.0009217166807502508, -0.027816399931907654, 0.042348381131887436, 0.06346812844276428, -0.030670298263430595, 0.027489224448800087, 0.0314815454185009, 0.010220708325505257, 0.023876585066318512, 0.011568091809749603, -0.015477398410439491, -0.009889459237456322, -0.022833410650491714, -0.030152367427945137, -0.020773785188794136, -0.0022359585855156183, -0.0069099594838917255, -0.06232764944434166, 0.008681670762598515, 0.056596413254737854, -0.08407587558031082, 0.039964426308870316, 0.06256385147571564, -0.04063131660223007, -0.04794082045555115, 0.03362669423222542, 0.029440846294164658, 0.0687476098537445, 0.054691143333911896, 0.08941961079835892, -0.0009745663264766335, -0.0016498188488185406, -0.0034676860086619854, 0.026875585317611694, -0.08315390348434448, 0.021503912284970284, -0.020892759785056114, -0.003366834716871381, 0.042940638959407806, 0.06786756217479706, 0.0030169568490236998, -0.10298775881528854, -0.018486252054572105, 0.044562604278326035, -0.005196806509047747, -0.05577559024095535, -0.019362399354577065, -0.04162418842315674, 0.03611278906464577, 0.03568345308303833, 0.036726582795381546, 0.08014840632677078, -0.020520318299531937, 0.0007595983915962279, 0.06492069363594055, -0.04751620814204216, -0.01529841497540474, -0.07752961665391922, -0.005159902852028608, 0.05850867182016373, 0.01156667247414589, 0.05011157691478729, 0.017201555892825127, 0.0026869773864746094, 0.012791942805051804, 0.0064340378157794476, 0.013495705090463161, -0.02993651293218136, 0.0013461426133289933, -0.016258910298347473, -0.059470467269420624, 0.030230263248085976, 0.0329284705221653, -0.04532448574900627, -0.030386846512556076, 0.058940112590789795, -0.03956226631999016, 0.04364325851202011, -0.041122764348983765, 0.027123263105750084, -0.014802413061261177, 0.06079861894249916, -0.014512622728943825, -0.013911280781030655, 0.10233696550130844, 0.0028332173824310303, -0.026674890890717506, -0.08882984519004822, 0.015233462676405907, -0.018080512061715126, 0.010874303989112377, -0.02919517084956169, -0.005165057256817818, -0.012813831679522991, -0.03137547895312309, -0.03126656264066696, 0.0336809866130352, 0.027993127703666687, -0.02338244952261448, -0.05042675510048866, 0.021559258922934532, -0.0075604566372931, -0.029185611754655838, -0.026718255132436752, 0.06175490841269493, -0.03266606107354164, 0.00013549851428251714, 0.04625151678919792, -0.024181609973311424, 0.050965603440999985, 0.01848941296339035, -0.0065552107989788055, -0.05680283531546593, 0.028222311288118362, -0.001927254954352975, 0.009210032410919666, -0.03809411823749542, 0.015946798026561737, -0.050424959510564804, -0.01533369068056345, 0.03970729932188988, 0.007282438222318888, 0.0026067099533975124, -0.010899808257818222, 0.02226468361914158, -0.04686913266777992, 0.01821923442184925, -0.04251403734087944, 0.024637481197714806, 0.0005009289598092437, 0.015452218241989613, 0.045840583741664886, 0.029497109353542328, -0.042612217366695404, -0.042879585176706314, 0.052066873759031296, 0.024753648787736893, -0.029821844771504402, -0.002698535332456231, 0.03233620896935463, -0.030500484630465508, 0.07611006498336792, 0.04427481070160866, -0.03318718820810318, -0.018006326630711555, -0.04223021864891052, -0.03480387479066849, 0.012991771101951599, 0.031224364414811134, 0.06584592163562775, -0.020902389660477638, -0.035066816955804825, -0.051799625158309937, -0.0013433978892862797, 0.023796143010258675, -0.017174959182739258, 0.018132219091057777, 0.0017778623150661588, 0.08183728903532028, -0.06674226373434067, -0.014023694209754467, -0.04052937030792236, -0.01885250024497509, 0.07497001439332962, 0.02109067142009735, -0.00688131945207715, 0.05884692817926407, 0.009445770643651485, 0.027886975556612015, -0.0508052334189415, -0.034446168690919876, 0.03466735780239105, -0.0010553045431151986, 0.017650559544563293, 0.017024265602231026, 0.0397530198097229, 0.02107134275138378, 0.03146655112504959, 0.019339151680469513, -0.049614857882261276, 0.03469376266002655, 0.022682195529341698, -0.028618114069104195, 0.06096822768449783, -0.08967741578817368, -0.003356422996148467, 0.011754038743674755, -0.0037724280264228582, 0.020850330591201782, 0.006134416908025742, -0.019993623718619347, -0.03395552933216095, 0.008478114381432533, -0.015956584364175797, -0.02770540490746498, 0.0745919719338417, 0.009194615297019482, -0.01881750114262104, -0.06566599756479263, -0.03591601550579071, -0.03827187046408653, -0.0664638951420784, 0.01352955773472786, -0.00865687895566225, -0.013701502233743668, 0.01210640650242567, 0.008359873667359352, 0.03845156356692314, 0.004356013610959053, 0.04912031814455986, 0.008728794753551483, -0.06607989221811295, -0.02665093168616295, 0.04367655888199806, -0.028053458780050278, -0.001378255314193666, 0.05190173164010048, -0.11265579611063004, -0.03252829611301422, -0.03075668029487133, -0.04016784206032753, -0.12758541107177734, -0.012522004544734955, 0.05183107778429985, -0.010352280922234058, -0.024503687396645546, -0.14181964099407196, 0.06097407266497612, -0.040963657200336456, 0.042191408574581146, 0.05985138565301895, 0.010707567445933819, -0.0538703016936779, -0.0289749875664711, -0.03046250529587269, -0.02143947221338749, 0.04782417044043541, -0.0870312973856926, 0.04627490043640137, -0.01659521460533142, -0.014466645196080208, 0.05352461710572243, 0.04014008119702339, 0.001876594964414835, -0.022489918395876884, -0.008442364633083344, 0.024627376347780228, 0.02278313599526882, 0.036717407405376434, 0.012897714041173458, 0.0016485040541738272, -0.026040423661470413, -0.024762358516454697, -0.041957419365644455, -0.049243517220020294, -0.03390040993690491, 0.020379818975925446, 0.03814476355910301, -0.04070119932293892, 0.04283924028277397, -0.01322109717875719, 0.043020449578762054, 0.0325288288295269, -0.021718762814998627, -0.00219733826816082, -0.0018562809564173222, -0.019643574953079224, -0.018180612474679947, -0.016655853018164635, 0.12390592694282532, 0.012447146698832512, 0.08859261870384216, 0.003834039904177189, -0.010705772787332535, -0.026941178366541862, 0.016808753833174706, -0.023756487295031548, 0.010189628228545189, -0.07019215822219849, 0.05037800967693329, -0.006690886337310076, -0.013998457230627537, -0.0004678698896896094, 0.04834148287773132, -0.017119184136390686, 0.020891888067126274, -0.05317467823624611, 0.021929433569312096, 0.024931270629167557, 0.028618885204195976, 0.010965608060359955, 0.008637670427560806, -0.011193189769983292, -0.002130002249032259, 0.014836996793746948, 0.06381525844335556, -0.04377171769738197, 0.009738837368786335, -0.022817222401499748, 0.016177216544747353, 0.062394190579652786, 0.0011421351227909327, -0.04605142027139664, 0.035928014665842056, 0.0010498873889446259, 0.032238781452178955, -0.006367798428982496, 0.005840805359184742, -0.0470854751765728, 0.012079047970473766, -0.01652444340288639, -0.002462429692968726, -0.005335427820682526, -0.025605520233511925, 0.016597429290413857, -0.004798599518835545, -0.017099810764193535, 0.02820957638323307, -0.014606938697397709, -0.0033952523954212666, -0.0257173590362072, 0.00299259927123785, -0.06720662117004395, 0.04293326660990715, 0.0014027045108377934, -0.005852058995515108, 0.022187432274222374, -0.00833679735660553, -0.023967646062374115, 0.05741932988166809, 0.015937361866235733, 0.009861520491540432, -0.014224857091903687, 0.007079530507326126, -0.015132513828575611, -0.012689391151070595, 0.060660477727651596, -0.018545910716056824, -0.004170672036707401, 0.08784876018762589, 0.014740211889147758, -0.008282092399895191, 0.0011443474795669317, -0.01933734118938446, 0.0037872607354074717, -0.032563310116529465, 0.05807223170995712, -0.04167341813445091, 0.05433082580566406, -0.014733350835740566, 0.007238670252263546, 0.040385983884334564, -0.008419683203101158, -0.08979463577270508, -0.0017884274711832404, 0.07238983362913132, 0.014221370220184326, 0.013908515684306622, -0.04955306276679039, 0.013516579754650593, 0.011410343460738659, -0.03534772992134094, 0.0007760213920846581, 0.00585224200040102, -0.009621932171285152, -0.003870810614898801, 0.0294390469789505, 0.00824795849621296, -0.04314916953444481, -0.04139428213238716, -0.0619315542280674, 0.05427068844437599, 0.014309081248939037, -0.027876948937773705, 0.03419267013669014, 0.026185061782598495, -0.006157968658953905, 0.004059723578393459, -0.025487765669822693, -0.0007510966970585287, 0.012131982482969761, 0.01838885433971882, 0.004199801478534937, 0.023860057815909386, -0.023773644119501114, -0.00044666099711321294, 0.04302719607949257, -0.061828579753637314, 0.014414941892027855, -0.011338042095303535, 0.035593852400779724, -0.031119629740715027, 0.008947611786425114, 0.019893789663910866, 0.0033858558163046837, 0.03883621469140053, -0.031109405681490898, -0.007827810011804104, -0.019891466945409775, 0.023330574855208397, 0.05795729160308838, -0.03222137317061424, -0.005029918160289526, -0.010957052931189537, -0.018676966428756714, 0.009247912093997002, -0.009849912486970425, 0.03652336820960045, -0.03782351687550545, -0.024964844807982445, 0.07339705526828766, -0.05546306073665619, -0.04576821252703667, -0.022262269631028175, -0.07900889217853546, -0.009290996007621288, -0.0014157341793179512, -0.005211435258388519, 0.06259189546108246, -0.03495035320520401, 0.01149998139590025, -0.04869115725159645, 0.025420021265745163, 0.02061697654426098, 0.020997297018766403, 0.01392487995326519, 0.06601167470216751, 0.011459769681096077, 0.0644971951842308, 0.05089813098311424, 0.023188509047031403, -0.00726065831258893, 0.0005174067919142544, -0.007138718850910664, 0.037492670118808746, -0.0066526769660413265, 0.009817284531891346, -0.041509900242090225, -0.04358835890889168, -0.003930828534066677, 0.007561029866337776, -0.04437461122870445, -0.0053267222829163074, -0.05802459269762039, -0.01410958357155323, -0.000517042470164597, 0.01812685839831829, 0.021740121766924858, 0.0049219075590372086, 0.05620935559272766, -0.0038143182173371315, -0.013157164677977562, 0.049148354679346085, 0.027664341032505035, 0.033590517938137054, 0.002431803848594427, -0.007216442842036486, 0.01921246200799942, 0.019745197147130966, 0.03395551070570946, 0.013996622525155544, -0.09791717678308487, 0.03244621679186821, -0.004360944498330355, 0.006118112243711948, 0.007711214944720268, 0.03310619667172432, -0.04610039293766022, -0.006557852029800415, -0.0029208713676780462, -0.020168403163552284, -0.016402577981352806, 0.020611507818102837, 0.032257139682769775, 0.021215014159679413, -0.006740160286426544, 0.01240026019513607, 0.07499559223651886, 0.026954710483551025, -0.04006706923246384, 0.004638905171304941, 0.0010122627718374133, 0.09215783327817917, 0.03234955295920372, -0.07004483044147491, -0.01034390926361084, 0.007473781704902649, -0.05814054235816002, -0.02226693369448185, 0.02521611750125885, -0.023186007514595985, 0.006680999882519245, -0.014957662671804428, -0.016951818019151688, -0.023879792541265488, -0.011090198531746864, 0.037156544625759125, 0.021576734259724617, 0.007327165454626083, -0.013056324794888496, 0.008392523974180222, -0.0313173346221447, -0.05991150438785553, 0.04444141313433647, 0.02033878304064274, -0.022826099768280983, -0.06005522236227989, -0.015444092452526093, 0.01543578039854765, -0.013917041942477226, 0.0032761823385953903, 0.0576808862388134, 0.016885260120034218, -0.03373374789953232, 0.018559593707323074, -0.01699254848062992, 0.02981572411954403, 0.008293963968753815, -0.009671326726675034, -0.008478367701172829, -0.046793725341558456, 0.10495970398187637, 0.016289589926600456, 0.02899232506752014, -0.020764393731951714, -0.022793427109718323, -0.005370027385652065, -0.05687502399086952, -0.021697593852877617, 0.010455457493662834, -0.030421309173107147, -0.029065024107694626, -0.04031390696763992, 0.030686650425195694, -0.009876763448119164, 0.06721555441617966, -0.05371361970901489, 0.048568520694971085, 0.021099867299199104, -0.03743133321404457, -0.0012799176620319486, -0.025244969874620438, -0.009059988893568516, -0.024912765249609947, 0.05236614868044853, 0.005713790189474821, -0.0061571476981043816, -0.022104425355792046, -0.04662907496094704, 0.05568473041057587, 0.01476152054965496, -0.0453607514500618, -0.023828774690628052, -0.019155994057655334, -0.02234015241265297, -0.06715407222509384, 0.0153026869520545, 0.01566164754331112, 0.038634058088064194, -0.012578827328979969, -0.04908118396997452, -0.0045433673076331615, 0.009043521247804165, -0.01420271024107933, 0.045082367956638336, -0.03142059966921806, 0.0019654836505651474, 0.02769157662987709, -0.041538842022418976, -0.004980428144335747, -0.10383102297782898, 0.004927793052047491, -0.013822969049215317, 0.020477546378970146, 0.04011811316013336, 0.016311971470713615, -0.04384680092334747, -0.01439171563833952, -0.03947516530752182, -0.014931161887943745, -0.003356784349307418, -0.05403757095336914, 0.07158895581960678, -0.0731104165315628, -0.017404986545443535, -0.038762643933296204, -0.015084169805049896, 0.025681525468826294, -0.020453117787837982, -0.05256364122033119, 0.014938692562282085, 0.015311780385673046, -0.01694396883249283, 0.05903052166104317, 0.0006505953497253358, -0.04628351703286171, 0.008903121575713158, 0.020999012514948845, 0.04112906754016876, -0.03888577222824097, 0.006931870710104704, 0.003713684156537056, 0.03922278806567192, -0.006921706255525351, 0.015252682380378246, 0.012399488128721714, 0.07252249121665955, -0.013342656195163727, -0.00174096436239779, -0.017307879403233528, -0.026519775390625, -0.00641930615529418, -0.035633642226457596, 0.0063712624832987785, 0.01633306033909321, -0.0665520653128624, -0.0008031941251829267, 0.009044324047863483, -0.02392493188381195, 0.03780888393521309, -0.038904499262571335, 0.014209412038326263, 0.04008980095386505, -0.001954104984179139, 0.04767129570245743, -0.024575814604759216, -0.036129165440797806, 0.0011571909999474883, -0.03563236445188522, -0.025437260046601295, 0.023959709331393242, 0.016507236286997795, 0.002823981223627925, -0.0706430971622467, 0.015400432050228119, 0.05975256860256195, 0.04126853868365288, 0.0272964034229517, 0.024054234847426414, 0.02307109162211418, 0.07174000144004822, 0.09567534923553467, 0.006418695207685232, 0.010161120444536209, 0.020141277462244034, 0.03624943271279335, 0.03666321560740471, 0.028910038992762566, 0.049928296357393265, -0.060796719044446945, -0.010952095501124859, 0.02233629673719406, 0.009665806777775288, -0.02752256952226162, 0.029436618089675903, 0.01548680942505598, 0.008681869134306908, -0.05344419181346893, -0.008353126235306263, 0.0020069133024662733, 0.04656665772199631, -0.038513969630002975, -0.03981463238596916, 0.03334716707468033, -0.001106441137380898, 0.0033315466716885567, 0.004331724718213081, -0.00686954939737916, -0.00884385034441948, -0.019680902361869812, -0.026334062218666077, 0.01683932915329933, -0.0070899538695812225, 0.008772997185587883, 0.0613924004137516, 0.055267658084630966, 0.01794305071234703, -0.02100851759314537, 0.08905358612537384, 0.04296343773603439, -0.028831951320171356, 0.04332193732261658, -0.0009546049986965954, -0.0032539968378841877, 0.03153934329748154, -0.029617514461278915, 0.0008956799283623695, 0.006790990009903908, -0.019577104598283768, -0.039136044681072235, -0.046653252094984055, -0.046407077461481094, 0.06149129569530487, -0.037748366594314575, 0.06492961943149567, -0.04789922758936882, 0.0153989652171731, -0.07126404345035553, 0.040268220007419586, -0.004550508689135313, -0.01878177933394909, -0.008173724636435509, -0.0561586394906044, 0.019185995683073997, 0.0005209207301959395, 0.007082770112901926, 0.007676938083022833, -0.046233586966991425, -0.005629011895507574, 0.01037396490573883, -0.02547580562531948, -0.03491021320223808, 0.009461063891649246, 0.04940834268927574, 0.0024844093713909388, 0.004990256391465664, 0.05721823498606682, -0.026086818426847458, 0.016294915229082108, 0.0413874015212059, 0.05507827177643776, 0.023656783625483513, 0.01929851435124874, 0.05706740543246269, 0.0317055881023407, 0.0423477478325367, 0.012984033674001694, -0.009340335614979267, -0.03611397743225098, 0.013398868031799793, -0.01343697588890791, -0.021457046270370483, -0.017227770760655403, 0.0013712483923882246, -0.033608391880989075, 0.04034360870718956, -0.014754705131053925, 0.009214619174599648, 0.039282169193029404, 0.015464452095329762, -0.014067542739212513, -0.006850104313343763, -0.028251511976122856, 0.042318619787693024, 0.0010159544181078672, -0.07910285890102386, -0.05739985778927803, -0.014814876019954681, -0.013562212698161602, -0.010929439216852188, -0.044873498380184174, -0.029638737440109253, 0.018473532050848007, 0.04032357782125473, -0.01731247454881668, 0.004057781305164099, -0.014460071921348572, -0.04746546223759651, -0.022014109417796135, -0.010901376605033875, -0.004708027932792902, -0.03543029725551605, 0.0077417166903615, -0.02296663261950016, 0.03288859501481056, 0.014409753493964672, -0.005033222958445549, 0.027523403987288475]}
--------------------------------------------------
Línea 2:

In [4]:
import os
import time
import re
from google.cloud import aiplatform
from google.cloud import storage
from google.cloud import bigquery

# === CONFIGURACIÓN ===
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../../../bubbo-dfba0-47e395cdcdc7.json"

# Inicializar cliente
client = bigquery.Client(location="europe-southwest1")
dataset_id_destiny = "bubbo-dfba0.content"

In [5]:
query_title_counts = f"""
SELECT title, COUNT(*) AS count
FROM `{dataset_id_destiny}.unified_content`
GROUP BY title
ORDER BY count DESC
"""

title_counts = client.query(query_title_counts).to_dataframe()
title_counts.head(10)  # Muestra los 10 más comunes

c:\Users\Agustín\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\cloud\bigquery\table.py:1900: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

        title  count
0   Episode 1  30052
1   Episode 2  29692
2   Episode 3  28632
3   Episode 4  27064
4   Episode 5  24802
5   Episode 6  23728
6   Episode 7  18120
7   Episode 8  17092
8   Episode 9  13144
9  Episode 10  12864

In [6]:
title_counts

                                 title  count
0                            Episode 1  30052
1                            Episode 2  29692
2                            Episode 3  28632
3                            Episode 4  27064
4                            Episode 5  24802
...                                ...    ...
3305891      PROfishing team с.1 с.151      2
3305892   Доктор Комаровський с.1 с.86      2
3305893  Олександр Пилипенко с.2 с.181      2
3305894      Паризькі таємниці с.1 с.2      2
3305895                    会读心术的那小子_03      2

[3305896 rows x 2 columns]

In [7]:
query_tmdb_counts = f"""
SELECT tmdb_id, COUNT(*) AS count
FROM `{dataset_id_destiny}.unified_content`
GROUP BY tmdb_id
ORDER BY count DESC
"""

tmdb_counts = client.query(query_tmdb_counts).to_dataframe()
tmdb_counts.head(10)  # Muestra los 10 más comunes

c:\Users\Agustín\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\cloud\bigquery\table.py:1900: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  tmdb_id  count
0     121   1276
1     120   1264
2     105   1184
3     122   1166
4  835017   1048
5     330   1032
6   75709   1026
7     808   1022
8     809   1014
9    9799   1006

In [8]:
tmdb_counts

          tmdb_id  count
0             121   1276
1             120   1264
2             105   1184
3             122   1166
4          835017   1048
...           ...    ...
4223816  25975123      2
4223817  24662709      2
4223818  24653624      2
4223819  24638755      2
4223820  24790534      2

[4223821 rows x 2 columns]